# CompactGUI Localisation
# @version 1

# ===================
# Translations

"Add" = "Add"
"Add Folder to Queue" = "Add Folder to Queue"
"Add a custom folder to the watchlist" = "Add a custom folder to the watchlist"
"Add to Compression Queue" = "Add to Compression Queue"
"Add to compression queue" = "Add to compression queue"
"Add to right-click context menu" = "Add to right-click context menu"
"Add to start menu" = "Add to start menu"
"Added to Queue" = "Added to Queue"
"Admin" = "Admin"
"Aggression of online skiplist" = "Aggression of online skiplist"
"Always show details on Compression Mode buttons" = "Always show details on Compression Mode buttons"
"Analysing" = "Analysing"
"Applied to all folders" = "Applied to all folders"
"Apply to all" = "Apply to all"
"Ascending" = "Ascending"
"Awaiting Compression" = "Awaiting Compression"
"Background Watcher Settings" = "Background Watcher Settings"
"Cancel" = "Cancel"
"Cancel Background Compressor" = "Cancel Background Compressor"
"Cancel operation" = "Cancel operation"
"Cancelling..." = "Cancelling..."
"Cannot remove folder" = "Cannot remove folder"
"Check for pre-release updates" = "Check for pre-release updates"
"Click to download" = "Click to download"
"CompactGUI" = "CompactGUI"
"Compress Again" = "Compress Again"
"Compress All Now" = "Compress All Now"
"Compress Selected" = "Compress Selected"
"Compress folders: " = "Compress folders: "
"Compressed" = "Compressed"
"Compressing..." = "Compressing..."
"Compression" = "Compression"
"Compression DB" = "Compression DB"
"Compression Mode" = "Compression Mode"
"Compression Settings" = "Compression Settings"
"Compression Summary" = "Compression Summary"
"Compression options have been applied to all folders" = "Compression options have been applied to all folders"
"Configuration" = "Configuration"
"Current Size" = "Current Size"
"Database Results" = "Database Results"
"Descending" = "Descending"
"Do not compress" = "Do not compress"
"Drive unavailable" = "Drive unavailable"
"Edit skip list for this folder" = "Edit skip list for this folder"
"Estimate Compression for non-Steam Folders (beta)" = "Estimate Compression for non-Steam Folders (beta)"
"Estimated size" = "Estimated size"
"Exit" = "Exit"
"Extensions in this folder" = "Extensions in this folder"
"Failed to submit to wiki" = "Failed to submit to wiki"
"Files Compressed" = "Files Compressed"
"Filetype Management" = "Filetype Management"
"For Steam Games, this uses the database to determine types to skip. For non-Steam folders this is based on the smart analyser." = "For Steam Games, this uses the database to determine types to skip. For non-Steam folders this is based on the smart analyser."
"For Steam games only.\nWhen choosing to skip user-submitted filetypes, this setting determines how many submissions are required for each filetype to consider skipping it. \n'low' is generally best, as higher options run the risk of skipping files that would otherwise compress well." = "For Steam games only.\nWhen choosing to skip user-submitted filetypes, this setting determines how many submissions are required for each filetype to consider skipping it. \n'low' is generally best, as higher options run the risk of skipping files that would otherwise compress well."
"Game" = "Game"
"Game Name" = "Game Name"
"Games" = "Games"
"Go to Database Results" = "Go to Database Results"
"HDDs only use 1 thread" = "HDDs only use 1 thread"
"Home" = "Home"
"Include global skipped file types" = "Include global skipped file types"
"Include smart skipped file types" = "Include smart skipped file types"
"Insufficient permission to access this folder" = "Insufficient permission to access this folder"
"LZX" = "LZX"
"Last Fetched: {0:dd MMM yyyy HH:mm:ss}" = "Last Fetched: {0:dd MMM yyyy HH:mm:ss}"
"Last analysed {0}" = "Last analysed {0}"
"Last ran: {0:dd MMM yyyy} at {0:HH:mm:ss}" = "Last ran: {0:dd MMM yyyy} at {0:HH:mm:ss}"
"Manage local skipped filetypes" = "Manage local skipped filetypes"
"Max Savings" = "Max Savings"
"Maximum Compression Threads" = "Maximum Compression Threads"
"Mode" = "Mode"
"Monitor compressed folders for changes" = "Monitor compressed folders for changes"
"Never" = "Never"
"Next scheduled: {0:dd MMM yyyy} at {0:HH:mm:ss}" = "Next scheduled: {0:dd MMM yyyy} at {0:HH:mm:ss}"
"No installed Steam games were found." = "No installed Steam games were found."
"No wiki data" = "No wiki data"
"Not Compressed" = "Not Compressed"
"On Schedule" = "On Schedule"
"On Schedule if system is also idle" = "On Schedule if system is also idle"
"Open" = "Open"
"Open Settings Folder" = "Open Settings Folder"
"Operation cancelled." = "Operation cancelled."
"Operation failed: {0}" = "Operation failed: {0}"
"Please check your internet connection and try again" = "Please check your internet connection and try again"
"Please wait until the current operation is finished" = "Please wait until the current operation is finished"
"Quickly parses over files and estimates their compression ratio without writing to disk. This will likely be super laggy on HDDs!" = "Quickly parses over files and estimates their compression ratio without writing to disk. This will likely be super laggy on HDDs!"
"Re-analyse all watched folders" = "Re-analyse all watched folders"
"Re-analyse this folder" = "Re-analyse this folder"
"Recently Updated" = "Recently Updated"
"Reload Languages.\nChecks online for updated language definitions" = "Reload Languages.\nChecks online for updated language definitions"
"Reload Steam Library list" = "Reload Steam Library list"
"Remove from Watchlist" = "Remove from Watchlist"
"Reset" = "Reset"
"Restart as Admin" = "Restart as Admin"
"Savings" = "Savings"
"Scanning installed Steam games..." = "Scanning installed Steam games..."
"Search by game name or SteamID..." = "Search by game name or SteamID..."
"Select a folder to compress" = "Select a folder to compress"
"Settings" = "Settings"
"Show notification on completion" = "Show notification on completion"
"Sort By" = "Sort By"
"Space Saved" = "Space Saved"
"Start CompactGUI in system tray" = "Start CompactGUI in system tray"
"Status" = "Status"
"Steam Library" = "Steam Library"
"SteamID" = "SteamID"
"Submit Results" = "Submit Results"
"Submitted to wiki" = "Submitted to wiki"
"Success" = "Success"
"System Integration" = "System Integration"
"The SnackbarPresenter was never set" = "The SnackbarPresenter was never set"
"This game uses DirectStorage technology. If you are using this feature, you should not compress this game." = "This game uses DirectStorage technology. If you are using this feature, you should not compress this game."
"Total Results" = "Total Results"
"UI Settings" = "UI Settings"
"UID" = "UID"
"Uncompress" = "Uncompress"
"Uncompressed" = "Uncompressed"
"Uncompressing..." = "Uncompressing..."
"Unknown" = "Unknown"
"Update Available" = "Update Available"
"Update Available ▸ Version {0}" = "Update Available ▸ Version {0}"
"Update Settings" = "Update Settings"
"Update in Steam" = "Update in Steam"
"Use skip list" = "Use skip list"
"Version" = "Version"
"Watch folder for changes" = "Watch folder for changes"
"Watched Folders" = "Watched Folders"
"Watcher" = "Watcher"
"WatcherPage" = "WatcherPage"
"When System is Idle" = "When System is Idle"
"Working" = "Working"
"XPRESS 16K" = "XPRESS 16K"
"XPRESS 4K" = "XPRESS 4K"
"XPRESS 8K" = "XPRESS 8K"
"Yes" = "Yes"
"You currently have {0} folders being watched. Closing CompactGUI will stop them from being monitored.{1}{1}Are you sure you want to exit?" = "You currently have {0} folders being watched. Closing CompactGUI will stop them from being monitored.{1}{1}Are you sure you want to exit?"
"can be saved" = "can be saved"
"contained files" = "contained files"
"day(s)" = "day(s)"
"edit" = "edit"
"edit skipped filetypes" = "edit skipped filetypes"
"every" = "every"
"games" = "games"
"just now" = "just now"
"last compressed:" = "last compressed:"
"last modified:" = "last modified:"
"select a folder" = "select a folder"
"uncompressed size" = "uncompressed size"
"{0:0} days ago" = "{0:0} days ago"
"{0:0} hours ago" = "{0:0} hours ago"
"{0:0} minutes ago" = "{0:0} minutes ago"
"{0} files will be skipped" = "{0} files will be skipped"
"{0} saved" = "{0} saved"
"{0}% decayed" = "{0}% decayed"

[context."Background Scheduler"]
"CompactGUI is running a scheduled task and will compress monitored folders in the background" = "CompactGUI is running a scheduled task and will compress monitored folders in the background"
"Next scheduled task is on {0}" = "Next scheduled task is on {0}"
"Scheduled Compression Completed" = "Scheduled Compression Completed"
"Scheduled Compression Running" = "Scheduled Compression Running"

[context."Compression estimate"]
"unknown" = "unknown"

[context."Compression size"]
"After" = "After"
"Before" = "Before"

[context."File size"]
"B" = "B"
"EB" = "EB"
"GB" = "GB"
"KB" = "KB"
"MB" = "MB"
"PB" = "PB"
"TB" = "TB"

[context."Folder status"]
"Unknown" = "Unknown"

[context."Relative date"]
"Unknown" = "Unknown"

[context."Schedule"]
"at" = "at"

[context."Skiplist aggression"]
"high" = "high"
"low" = "low"
"medium" = "medium"

[context."Skiplist editor"]
"Save" = "Save"

[context."Steam Library Compression Mode Button"]
"Compress | {0}" = "Compress | {0}"

[context."Steam Library Tab Headings"]
"CURRENT SIZE" = "CURRENT SIZE"
"GAME" = "GAME"
"RECOMMENDED ACTION" = "RECOMMENDED ACTION"
"SAVINGS" = "SAVINGS"
"STATUS" = "STATUS"

[context."Storage savings"]
"saved" = "saved"
