# CompactGUI Localisation
# @version 1

# ===================
# Translations

"Add" = "추가하기"
"Add Folder to Queue" = "새로운 폴더 추가"
"Add a custom folder to the watchlist" = "모니터링 리스트에 커스텀 폴더 추가"
"Add to Compression Queue" = "압축 대기열에 추가"
"Add to compression queue" = "압축 대기열에 추가"
"Add to right-click context menu" = "우클릭 메뉴에 추가"
"Add to start menu" = "시작 메뉴에 추가"
"Added to Queue" = "대기열에 추가되었습니다"
"Admin" = "관리자"
"Aggression of online skiplist" = "온라인 제외 리스트 적용 강도"
"Always show details on Compression Mode buttons" = "압축 모드 버튼에 세부 정보 항상 표시"
"Analysing" = "분석 중"
"Applied to all folders" = "모든 폴더에 적용되었습니다"
"Apply to all" = "모든 폴더에 적용"
"Ascending" = "오름차순"
"Awaiting Compression" = "압축 대기 중"
"Background Watcher Settings" = "백그라운드 모니터링 설정"
"Cancel" = "취소"
"Cancel Background Compressor" = "백그라운드 압축 취소"
"Cancel operation" = "작업 취소"
"Cancelling..." = "취소 중..."
"Cannot remove folder" = "폴더를 대기열에서 제거할 수 없습니다"
"Check for pre-release updates" = "프리릴리스 업데이트까지 확인"
"Click to download" = "클릭해서 다운로드"
"CompactGUI" = "CompactGUI"
"Compress Again" = "재압축"
"Compress All Now" = "전부 압축"
"Compress Selected" = "선택한 폴더 압축"
"Compress folders: " = "폴더 압축 시점: "
"Compressed" = "압축됨"
"Compressing..." = "압축 중..."
"Compression" = "압축"
"Compression DB" = "압축 데이터베이스"
"Compression Mode" = "압축 모드"
"Compression Settings" = "압축 설정"
"Compression Summary" = "압축 결과"
"Compression options have been applied to all folders" = "압축 설정이 모든 폴더에 적용되었습니다"
"Configuration" = "설정"
"Current Size" = "현재 크기"
"Database Results" = "압축 데이터 목록"
"Descending" = "내림차순"
"Direct Storage" = "DirectStorage"
"Do not compress" = "압축하지 않기"
"Drive unavailable" = "드라이브 사용 불가"
"Edit skip list for this folder" = "이 폴더에서 제외할 항목 편집"
"Estimate Compression for non-Steam Folders (beta)" = "Steam 외의 폴더도 압축량 추정 (베타)"
"Estimated size" = "예상 크기"
"Exit" = "종료"
"Extensions in this folder" = "이 폴더의 파일 확장자"
"Failed to submit to wiki" = "위키 제출에 실패했습니다"
"Files Compressed" = "압축한 파일 수"
"Filetype Management" = "파일 확장자 관리"
"For Steam Games, this uses the database to determine types to skip. For non-Steam folders this is based on the smart analyser." = "Steam 게임은 데이터베이스를, 그 외 폴더는 분석 결과를 바탕으로 제외할 파일 형식을 자동으로 정합니다."
"For Steam games only.\nWhen choosing to skip user-submitted filetypes, this setting determines how many submissions are required for each filetype to consider skipping it. \n'low' is generally best, as higher options run the risk of skipping files that would otherwise compress well." = "다른 사용자들이 제출한 정보를 바탕으로 파일 형식을 얼마나 적극적으로 제외할지 설정합니다.\n\n일반적으로는 '약하게'가 적합하며, 더 강하게 설정하면 압축이 잘 되는 파일까지 제외할 수 있습니다.\n\nSteam 게임에서만 적용됩니다."
"Game" = "게임"
"Game Name" = "게임 이름"
"Games" = "개"
"Go to Database Results" = "압축 데이터 목록으로 이동"
"HDDs only use 1 thread" = "하드 디스크일 경우 하나의 스레드만 사용"
"Home" = "홈"
"Include global skipped file types" = "공통으로 제외할 파일 형식 포함"
"Include smart skipped file types" = "자동으로 제외할 파일 형식 포함"
"Insufficient permission to access this folder" = "이 폴더에 접근할 권한이 부족합니다"
"LZX" = "LZX"
"Last Fetched: {0:dd MMM yyyy HH:mm:ss}" = "마지막 확인: {0:yyyy년 M월 d일 HH:mm:ss}"
"Last analysed {0}" = "마지막 분석 시점: {0}"
"Last ran: {0:dd MMM yyyy} at {0:HH:mm:ss}" = "마지막 실행 시점: {0:yyyy년 M월 d일 HH:mm:ss}"
"Manage local skipped filetypes" = "압축하지 않을 파일 확장자 관리"
"Max Savings" = "최대 절감률"
"Maximum Compression Threads" = "최대 압축 스레드 수"
"Mode" = "압축 방식"
"Monitor compressed folders for changes" = "압축된 폴더에 변경 사항이 있는지 모니터링"
"Never" = "사용 안 함"
"Next scheduled: {0:dd MMM yyyy} at {0:HH:mm:ss}" = "다음 예약 시점: {0:yyyy년 M월 d일 HH:mm:ss}"
"No installed Steam games were found." = "설치된 Steam 게임을 발견하지 못했습니다."
"No wiki data" = "위키 데이터 없음"
"Not Compressed" = "압축되지 않음"
"On Schedule" = "예약한 시점에 수행"
"On Schedule if system is also idle" = "예약한 시점인 동시에 시스템이 유휴 상태일 때 수행"
"Open" = "열기"
"Open Settings Folder" = "설정 폴더 열기"
"Operation cancelled." = "작업이 취소되었습니다."
"Operation failed: {0}" = "작업에 실패했습니다: {0}"
"Please check your internet connection and try again" = "인터넷 연결을 확인한 후 다시 시도해주세요"
"Please wait until the current operation is finished" = "현재 작업이 완료되기 전까지 기다려 주세요"
"Quickly parses over files and estimates their compression ratio without writing to disk. This will likely be super laggy on HDDs!" = "디스크에 쓰지 않고 파일을 빠르게 분석하여 압축률을 추정합니다. 하드 디스크를 사용하는 경우 매우 느려질 수 있습니다."
"Re-analyse all watched folders" = "모니터링 중인 모든 폴더 재분석"
"Re-analyse this folder" = "이 폴더 재분석"
"Recently Updated" = "최근 업데이트됨"
"Reload Languages.\nChecks online for updated language definitions" = "언어 새로고침\n온라인에서 업데이트된 번역 파일을 확인합니다"
"Reload Steam Library list" = "Steam 라이브러리 목록 새로고침"
"Remove from Watchlist" = "모니터링 리스트에서 제거"
"Reset" = "초기화"
"Restart as Admin" = "관리자 권한으로 재시작"
"Savings" = "절감률"
"Scanning installed Steam games..." = "설치된 Steam 게임 스캔 중..."
"Search by game name or SteamID..." = "게임 이름 또는 Steam ID로 검색..."
"Select a folder to compress" = "압축할 폴더 선택"
"Settings" = "설정"
"Show notification on completion" = "완료 시 알림"
"Sort By" = "정렬 기준"
"Space Saved" = "절약된 공간"
"Start CompactGUI in system tray" = "CompactGUI를 시스템 트레이에서 시작"
"Status" = "상태"
"Steam Library" = "Steam 라이브러리"
"SteamID" = "Steam ID"
"Submit Results" = "결과 제출"
"Submitted to wiki" = "위키에 제출되었습니다"
"Success" = "성공"
"System Integration" = "시스템 연동"
"The SnackbarPresenter was never set" = "SnackbarPresenter가 설정되어 있지 않습니다"
"This game uses DirectStorage technology. If you are using this feature, you should not compress this game." = "이 게임은 DirectStorage 기술을 사용합니다. 이 기능을 사용 중이라면 이 게임을 압축하지 않는 것이 좋습니다."
"Total Results" = "제출된 결과 수"
"UI Settings" = "UI 설정"
"UID" = "UID"
"Uncompress" = "압축 해제"
"Uncompressed" = "압축되지 않음"
"Uncompressing..." = "압축 해제 중..."
"Unknown" = "알 수 없음"
"Update Available" = "업데이트 가능"
"Update Available ▸ Version {0}" = "업데이트가 가능합니다 ▸ 버전: {0}"
"Update Settings" = "업데이트 설정"
"Update in Steam" = "Steam에서 업데이트"
"Use skip list" = "제외 리스트 사용"
"Version" = "버전"
"Watch folder for changes" = "폴더 변경 사항 모니터링"
"Watched Folders" = "모니터링 리스트"
"Watcher" = "모니터링"
"WatcherPage" = "모니터링 페이지"
"When System is Idle" = "시스템이 유휴 상태일 때 수행"
"Working" = "작업 중"
"XPRESS 16K" = "XPRESS 16K"
"XPRESS 4K" = "XPRESS 4K"
"XPRESS 8K" = "XPRESS 8K"
"Yes" = "예"
"You currently have {0} folders being watched. Closing CompactGUI will stop them from being monitored.{1}{1}Are you sure you want to exit?" = "{0}개의 모니터링 중인 폴더가 있습니다. CompactGUI를 종료하면 모니터링이 중단됩니다.{1}{1}정말 종료할까요?"
"can be saved" = "절약 가능"
"contained files" = "파일 수"
"day(s)" = "일"
"edit" = "편집"
"edit skipped filetypes" = "압축에서 제외할 파일 확장자"
"every" = "매"
"games" = "개"
"just now" = "방금 전"
"last compressed:" = "마지막 압축:"
"last modified:" = "마지막 수정:"
"select a folder" = "폴더를 선택하세요"
"uncompressed size" = "압축 전 크기"
"{0:0} days ago" = "{0:0}일 전"
"{0:0} hours ago" = "{0:0}시간 전"
"{0:0} minutes ago" = "{0:0}분 전"
"{0} files will be skipped" = "{0}개의 파일이 제외됩니다"
"{0} saved" = "{0} 절약됨"
"{0}% decayed" = "압축 효과 {0}% 감소"

[context."Background Scheduler"]
"CompactGUI is running a scheduled task and will compress monitored folders in the background" = "CompactGUI가 예약된 작업을 실행 중이며 모니터링 중인 폴더를 백그라운드에서 압축합니다"
"Next scheduled task is on {0}" = "다음 예약 작업은 {0}에 실행됩니다"
"Scheduled Compression Completed" = "예약 압축 완료"
"Scheduled Compression Running" = "예약 압축 실행 중"

[context."Compression estimate"]
"unknown" = "알 수 없음"

[context."Compression size"]
"After" = "압축 후"
"Before" = "압축 전"

[context."File size"]
"B" = "B"
"EB" = "EB"
"GB" = "GB"
"KB" = "KB"
"MB" = "MB"
"PB" = "PB"
"TB" = "TB"

[context."Folder status"]
"Unknown" = "알 수 없음"

[context."Relative date"]
"Unknown" = "알 수 없음"

[context."Schedule"]
"at" = ""

[context."Skiplist aggression"]
"high" = "강하게"
"low" = "약하게"
"medium" = "보통"

[context."Skiplist editor"]
"Save" = "저장"

[context."Steam Library Compression Mode Button"]
"Compress | {0}" = "압축 | {0}"

[context."Steam Library Tab Headings"]
"CURRENT SIZE" = "현재 크기"
"GAME" = "게임"
"RECOMMENDED ACTION" = "권장 작업"
"SAVINGS" = "절감량"
"STATUS" = "상태"

[context."Storage savings"]
"saved" = "절약됨"