schema = 1

[locales."en-AU"]
version = 1
file = "en-AU.toml"

[locales."es-ES"]
version = 1
file = "es-ES.toml"

[locales."ko-KR"]
version = 1
file = "ko-KR.toml"

[locales."ru-RU"]
version = 1
file = "ru-RU.toml"

[locales."zh-CN"]
version = 2
file = "zh-CN.toml"

[locales."it-IT"]
version = 1
file = "it-IT.toml"

[locales."tr-TR"]
version = 1
file = "tr-TR.toml"

[locales."id-ID"]
version = 1
file = "id-ID.toml"
