# CompactGUI Localisation
# @version 1

# ===================
# Translations

"Add" = "Добавить"
"Add Folder to Queue" = "Добавить папку в очередь"
"Add a custom folder to the watchlist" = "Добавить свою папку в список отслеживания"
"Add to Compression Queue" = "Add to Compression Queue" # LOC:TODO
"Add to compression queue" = "Добавить в очередь сжатия"
"Add to right-click context menu" = "Добавить в контекстное меню правой кнопки мыши"
"Add to start menu" = "Добавить в меню «Пуск»"
"Added to Queue" = "Добавлено в очередь"
"Admin" = "Администратор"
"Aggression of online skiplist" = "Уровень агрессивности онлайн-списка пропуска"
"Always show details on Compression Mode buttons" = "Всегда показывать подробности на кнопках режимов сжатия"
"Analysing" = "Анализ"
"Applied to all folders" = "Применено ко всем папкам"
"Apply to all" = "Применить ко всем"
"Ascending" = "По возрастанию"
"Awaiting Compression" = "Ожидание сжатия"
"Background Watcher Settings" = "Настройки фонового отслеживания"
"Cancel" = "Отмена"
"Cancel Background Compressor" = "Отменить фоновое сжатие"
"Cancel operation" = "Cancel operation" # LOC:TODO
"Cancelling..." = "Cancelling..." # LOC:TODO
"Cannot remove folder" = "Не удаётся удалить папку"
"Check for pre-release updates" = "Проверять предварительные версии обновлений"
"Click to download" = "Нажмите, чтобы скачать"
"CompactGUI" = "CompactGUI"
"Compress Again" = "Сжать заново"
"Compress All Now" = "Сжать всё сейчас"
"Compress Selected" = "Сжать выбранное"
"Compress folders: " = "Сжимать папки: "
"Compressed" = "Сжато"
"Compressing..." = "Compressing..." # LOC:TODO
"Compression" = "Сжатие"
"Compression DB" = "База сжатия"
"Compression Mode" = "Режим сжатия"
"Compression Settings" = "Настройки сжатия"
"Compression Summary" = "Сводка сжатия"
"Compression options have been applied to all folders" = "Параметры сжатия применены ко всем папкам"
"Configuration" = "Конфигурация"
"Current Size" = "Current Size" # LOC:TODO
"Database Results" = "Результаты базы данных"
"Descending" = "По убыванию"
"Do not compress" = "Do not compress" # LOC:TODO
"Edit skip list for this folder" = "Изменить список исключений для этой папки"
"Estimate Compression for non-Steam Folders (beta)" = "Оценивать сжатие для папок не из Steam (бета)"
"Estimated size" = "Предполагаемый размер"
"Exit" = "Выход"
"Extensions in this folder" = "Расширения в этой папке"
"Failed to submit to wiki" = "Не удалось отправить в Вики"
"Files Compressed" = "Файлов сжато"
"Filetype Management" = "Управление типами файлов"
"For Steam Games, this uses the database to determine types to skip. For non-Steam folders this is based on the smart analyser." = "Для игр Steam используется база данных для определения пропускаемых типов. Для папок не из Steam это основано на умном анализаторе."
"For Steam games only.\nWhen choosing to skip user-submitted filetypes, this setting determines how many submissions are required for each filetype to consider skipping it. \n'low' is generally best, as higher options run the risk of skipping files that would otherwise compress well." = "Только для игр Steam.\nПри выборе пропуска файлов, предложенных пользователями, этот параметр определяет, сколько подтверждений необходимо для каждого типа файлов, чтобы его пропускать.\n«Низкий» обычно оптимален, так как более высокие значения могут привести к пропуску файлов, которые на самом деле хорошо сжимаются."
"Game" = "Игра"
"Game Name" = "Названию игры"
"Games" = "Игры"
"Go to Database Results" = "Go to Database Results" # LOC:TODO
"HDDs only use 1 thread" = "Для HDD использовать только 1 поток"
"Home" = "Главная"
"Include global skipped file types" = "Включить глобальный список пропускаемых типов"
"Include smart skipped file types" = "Включить умные пропускаемые типы файлов"
"Insufficient permission to access this folder" = "Недостаточно прав для доступа к этой папке"
"LZX" = "LZX" # LOC:TODO
"Last Fetched: {0:dd MMM yyyy HH:mm:ss}" = "Последнее получение: {0:dd MMM yyyy HH:mm:ss}"
"Last analysed {0}" = "Последний анализ {0}"
"Last ran: {0:dd MMM yyyy} at {0:HH:mm:ss}" = "Последний запуск: {0:dd MMM yyyy} в {0:HH:mm:ss}"
"Manage local skipped filetypes" = "Управление локальным списком пропускаемых типов файлов"
"Max Savings" = "Максимальной экономии"
"Maximum Compression Threads" = "Максимум потоков сжатия"
"Mode" = "Режим"
"Monitor compressed folders for changes" = "Отслеживать изменения в сжатых папках"
"Never" = "Никогда"
"Next scheduled: {0:dd MMM yyyy} at {0:HH:mm:ss}" = "Следующее по расписанию: {0:dd MMM yyyy} в {0:HH:mm:ss}"
"No installed Steam games were found." = "No installed Steam games were found." # LOC:TODO
"No wiki data" = "No wiki data" # LOC:TODO
"Not Compressed" = "Не сжато"
"On Schedule" = "По расписанию"
"On Schedule if system is also idle" = "По расписанию, если система также бездействует"
"Open" = "Открыть"
"Open Settings Folder" = "Открыть папку настроек"
"Operation cancelled." = "Operation cancelled." # LOC:TODO
"Operation failed: {0}" = "Operation failed: {0}" # LOC:TODO
"Please check your internet connection and try again" = "Проверьте подключение к интернету и повторите попытку"
"Please wait until the current operation is finished" = "Подождите завершения текущей операции"
"Re-analyse all watched folders" = "Переанализировать все отслеживаемые папки"
"Re-analyse this folder" = "Повторно проанализировать эту папку"
"Recently Updated" = "Recently Updated" # LOC:TODO
"Reload Languages.\nChecks online for updated language definitions" = "Reload Languages.\nChecks online for updated language definitions" # LOC:TODO
"Reload Steam Library list" = "Reload Steam Library list" # LOC:TODO
"Remove from Watchlist" = "Удалить из списка отслеживания"
"Reset" = "Сбросить"
"Restart as Admin" = "Перезапустить от имени администратора"
"Savings" = "Экономия"
"Scanning installed Steam games..." = "Scanning installed Steam games..." # LOC:TODO
"Search by game name or SteamID..." = "Поиск по названию игры или SteamID..."
"Settings" = "Настройки"
"Show notification on completion" = "Показывать уведомление о завершении"
"Sort By" = "Сортировать по"
"Space Saved" = "Сэкономлено места"
"Start CompactGUI in system tray" = "Запускать CompactGUI в области уведомлений"
"Status" = "Status" # LOC:TODO
"Steam Library" = "Steam Library" # LOC:TODO
"SteamID" = "SteamID"
"Submit Results" = "Отправить результаты"
"Submitted to wiki" = "Отправлено в Вики"
"Success" = "Успешно"
"System Integration" = "Интеграция в систему"
"The SnackbarPresenter was never set" = "SnackbarPresenter не установлен"
"This game uses DirectStorage technology. If you are using this feature, you should not compress this game." = "Эта игра использует технологию DirectStorage. Если вы используете эту функцию, вам не следует сжимать эту игру."
"Total Results" = "Всего результатов"
"UI Settings" = "Настройки интерфейса"
"UID" = "UID" # LOC:TODO
"Uncompress" = "Распаковать"
"Uncompressed" = "Uncompressed" # LOC:TODO
"Uncompressing..." = "Uncompressing..." # LOC:TODO
"Unknown" = "Unknown" # LOC:TODO
"Update Available" = "Update Available" # LOC:TODO
"Update Available ▸ Version {0}" = "Доступно обновление ▸ Версия {0}"
"Update Settings" = "Настройки обновлений"
"Update in Steam" = "Update in Steam" # LOC:TODO
"Use skip list" = "Использовать список исключений"
"Version" = "Версия"
"Watch folder for changes" = "Отслеживать изменения в папке"
"Watched Folders" = "Отслеживаемые папки"
"Watcher" = "Наблюдение"
"WatcherPage" = "Страница отслеживания"
"When System is Idle" = "Когда система бездействует"
"Working" = "Выполняется"
"XPRESS 16K" = "XPRESS 16K" # LOC:TODO
"XPRESS 4K" = "XPRESS 4K" # LOC:TODO
"XPRESS 8K" = "XPRESS 8K" # LOC:TODO
"Yes" = "Да"
"You currently have {0} folders being watched. Closing CompactGUI will stop them from being monitored.{1}{1}Are you sure you want to exit?" = "В данный момент отслеживается папок ({0}). Закрытие CompactGUI прекратит их отслеживание.{1}{1}Вы уверены, что хотите выйти?"
"can be saved" = "can be saved" # LOC:TODO
"contained files" = "содержит файлов"
"day(s)" = "дн."
"edit" = "изменить"
"edit skipped filetypes" = "изменить список пропускаемых типов"
"every" = "каждые"
"games" = "games" # LOC:TODO
"just now" = "только что"
"last compressed:" = "последнее сжатие:"
"last modified:" = "последнее изменение:"
"select a folder" = "выберите папку"
"uncompressed size" = "исходный размер"
"{0:0} days ago" = "{0:0} дн. назад"
"{0:0} hours ago" = "{0:0} ч. назад"
"{0:0} minutes ago" = "{0:0} мин. назад"
"{0} files will be skipped" = "{0} files will be skipped" # LOC:TODO
"{0} saved" = "{0} сэкономлено"
"{0}% decayed" = "{0}% устарело"

[context."Compression estimate"]
"unknown" = "неизвестно"

[context."Compression size"]
"After" = "После"
"Before" = "До"

[context."File size"]
"B" = "б"
"EB" = "Эб"
"GB" = "Гб"
"KB" = "Кб"
"MB" = "Мб"
"PB" = "Пб"
"TB" = "Тб"

[context."Folder status"]
"Unknown" = "Неизвестно"

[context."Relative date"]
"Unknown" = "Неизвестно"

[context."Schedule"]
"at" = "в"

[context."Skiplist aggression"]
"high" = "высокий"
"low" = "низкий"
"medium" = "средний"

[context."Skiplist editor"]
"Save" = "Сохранить"

[context."Steam Library Compression Mode Button"]
"Compress | {0}" = "Compress | {0}" # LOC:TODO

[context."Steam Library Tab Headings"]
"CURRENT SIZE" = "CURRENT SIZE" # LOC:TODO
"GAME" = "GAME" # LOC:TODO
"RECOMMENDED ACTION" = "RECOMMENDED ACTION" # LOC:TODO
"SAVINGS" = "SAVINGS" # LOC:TODO
"STATUS" = "STATUS" # LOC:TODO

[context."Storage savings"]
"saved" = "сэкономлено"

[obsolete]
"Custom list — {0} entries" = "Свой список — {0} записей"
"Custom: {0} entries" = "Свой: {0} записей"
"DB — {0} files" = "Вики — {0} файлов"
"For Steam Games:\nskips files based on database results\n\nFor Non-Steam Folders:\nskips files based on compression estimate" = "Для игр Steam:\nпропускает файлы на основе результатов базы данных\n\nДля папок не из Steam:\nпропускает файлы на основе оценки сжатия"
"Global + DB — {0} files" = "Глобальный + Вики — {0} файлов"
"Global — {0} files" = "Глобальный — {0} файлов"
"Global: {0} skipped" = "Глобальный: {0} пропущено"
"Language (Requires Restart)" = "Язык (требуется перезапуск)"
"Language Changed" = "Язык изменён"
"Language changed successfully. You may need to restart the application for all changes to take effect." = "Смена языка выполнена. Возможно, потребуется перезапустить приложение, чтобы все изменения вступили в силу."
"Last analysed" = "Последний анализ"
"OK" = "хорошо"
"Off" = "Выкл"
"Results State" = "Состояние результатов"
"Skip file types likely to compress poorly" = "Пропускать типы файлов, которые сжимаются плохо"
"Skip file types specified in settings" = "Пропускать типы файлов, указанные в настройках"
"Smart: {0} skipped" = "Умный: {0} пропущено"
"Welcome" = "Добро пожаловать"
"decayed" = "устарело"
"files will be skipped" = "фл. будет пропущено"
"not configured" = "не настроено"
