# CompactGUI Localisation
# @version 1
# @programversion 4.0.0-beta.12

# ===================
# Translations

"Add" = "Ekle"
"Add a custom folder to the watchlist" = "─░zleme listesine ├Âzel klas├Âr ekle"
"Add selected to queue" = "Seçilenleri sıraya ekle"
"Add to Compression Queue" = "Sıkıştırma Sırasına Ekle"
"Add to compression queue" = "S─▒k─▒┼şt─▒rma kuyru─şuna ekle"
"Add to right-click context menu" = "Sa─ş t─▒k ba─şlam men├╝s├╝ne ekle"
"Add to start menu" = "Ba┼şlat men├╝s├╝ne ekle"
"Added to Queue" = "Kuyru─şa Eklendi"
"Admin" = "Y├Ânetici"
"Aggression of online skiplist" = "├çevrimi├ği atlama listesi agresifli─şi"
"Always show details on Compression Mode buttons" = "S─▒k─▒┼şt─▒rma Modu d├╝─şmelerinde her zaman ayr─▒nt─▒lar─▒ g├Âster"
"Analysing" = "Analiz Ediliyor"
"Analysing..." = "Analiz ediliyor..."
"Applied to all folders" = "T├╝m klas├Ârlere uyguland─▒"
"Ascending" = "Artan"
"Awaiting Compression" = "S─▒k─▒┼şt─▒rma Bekleniyor"
"Background Watcher Settings" = "Arkaplan ─░zleyici Ayarlar─▒"
"COMPARE METHODS" = "YÖNTEMLERİ KARŞILAŞTIR"
"COMPRESSION MODE " = "SIKIŞTIRMA MODU "
"Cancel" = "─░ptal"
"Cancel Background Compressor" = "Arkaplan S─▒k─▒┼şt─▒r─▒c─▒y─▒ ─░ptal Et"
"Cancel operation" = "İşlemi iptal et"
"Cannot remove folder" = "Klas├Âr kald─▒r─▒lam─▒yor"
"Check for pre-release updates" = "├ûn s├╝r├╝m g├╝ncellemelerini denetle"
"Choose Compression" = "Sıkıştırma Seç"
"Clear filters" = "Filtreleri temizle"
"Click to download" = "─░ndirmek i├ğin t─▒klay─▒n"
"CompactGUI" = "CompactGUI"
"Complete" = "Tamamlandı"
"Compress" = "Sıkıştır"
"Compress Again" = "Tekrar S─▒k─▒┼şt─▒r"
"Compress All Now" = "Hepsini ┼Şimdi S─▒k─▒┼şt─▒r"
"Compress Selected" = "Se├ğilenleri S─▒k─▒┼şt─▒r"
"Compress folders: " = "Klas├Ârleri s─▒k─▒┼şt─▒r: "
"Compressed" = "S─▒k─▒┼şt─▒r─▒ld─▒"
"Compressing..." = "Sıkıştırılıyor..."
"Compression" = "S─▒k─▒┼şt─▒rma"
"Compression DB" = "S─▒k─▒┼şt─▒rma Veritaban─▒"
"Compression Settings" = "S─▒k─▒┼şt─▒rma Ayarlar─▒"
"Compression Summary" = "S─▒k─▒┼şt─▒rma ├ûzeti"
"Compression options have been applied to all folders" = "S─▒k─▒┼şt─▒rma se├ğenekleri t├╝m klas├Ârlere uyguland─▒"
"Current Size" = "Mevcut Boyut"
"Database Results" = "Veritaban─▒ Sonu├ğlar─▒"
"Descending" = "Azalan"
"Deselect all" = "Tüm seçimleri kaldır"
"Direct Storage" = "Direct Storage"
"Disk space is low. Retrying affected files sequentially." = "Disk space is low. Retrying affected files sequentially." # LOC:TODO
"Do Not Compress" = "Sıkıştırma"
"Do not compress" = "Sıkıştırma"
"Drive unavailable" = "Sürücü kullanılamıyor"
"Edit list" = "Listeyi düzenle"
"Estimate Compression for non-Steam Folders (beta)" = "Steam d─▒┼ş─▒ klas├Ârler i├ğin s─▒k─▒┼şt─▒rmay─▒ tahmin et (beta)"
"Estimated Size" = "Tahmini Boyut"
"Estimated size" = "Tahmini boyut"
"Exit" = "├ç─▒k─▒┼ş"
"Extensions in this folder" = "Bu klas├Ârdeki uzant─▒lar"
"Failed" = "Başarısız"
"Failed to submit to wiki" = "Wiki'ye g├Ânderilemedi"
"Filetype Management" = "Dosya T├╝r├╝ Y├Ânetimi"
"Filter" = "Filtre"
"Finishing {0} active file operations; do not power off." = "{0} aktif dosya işlemi tamamlanıyor; bilgisayarı kapatmayın."
"For Steam Games, this uses the database to determine types to skip. For non-Steam folders this is based on the smart analyser." = "Steam Oyunlar─▒ i├ğin, atlanacak t├╝rleri belirlemek amac─▒yla veritaban─▒n─▒ kullan─▒r. Steam d─▒┼ş─▒ klas├Ârler i├ğin ak─▒ll─▒ analizciye dayan─▒r."
"For Steam games only.\nWhen choosing to skip user-submitted filetypes, this setting determines how many submissions are required for each filetype to consider skipping it. \n'low' is generally best, as higher options run the risk of skipping files that would otherwise compress well." = "Sadece Steam oyunlar─▒ i├ğin.\nKullan─▒c─▒ taraf─▒ndan g├Ânderilen dosya t├╝rlerinin atlanmas─▒ se├ğildi─şinde, bu ayar her bir dosya t├╝r├╝n├╝n atlanmas─▒ i├ğin ka├ğ g├Ânderim gerekti─şini belirler. \n'd├╝┼ş├╝k' genellikle en iyisidir, ├ğ├╝nk├╝ daha y├╝ksek se├ğenekler normalde iyi s─▒k─▒┼şabilecek dosyalar─▒n atlanmas─▒ riskini ta┼ş─▒r."
"Game" = "Oyun"
"Game Name" = "Oyun Ad─▒"
"Games" = "Oyunlar"
"Go to Database Results" = "Veritabanı Sonuçlarına Git"
"HDDs only use 1 thread" = "HDD'ler yaln─▒zca 1 i┼ş par├ğac─▒─ş─▒ kullans─▒n"
"Home" = "Giri┼ş"
"Include global skiplist" = "Genel atlama listesini dahil et"
"Include global skipped file types" = "Genel atlanan dosya t├╝rlerini dahil et"
"Include smart skiplist" = "Akıllı atlama listesini dahil et"
"Include smart skipped file types" = "Ak─▒ll─▒ atlanan dosya t├╝rlerini dahil et"
"Insufficient permission to access this folder" = "Bu klas├Âre eri┼şmek i├ğin yetersiz izin"
"LZX" = "LZX"
"Last Fetched: {0:dd MMM yyyy HH:mm:ss}" = "Son Alma: {0:dd MMM yyyy HH:mm:ss}"
"Last analysed {0}" = "Son analiz: {0}"
"Last ran: {0:dd MMM yyyy} at {0:HH:mm:ss}" = "Son çalışma: {0:dd MMM yyyy} saat {0:HH:mm:ss}"
"Library location" = "Kütüphane konumu"
"Manage local skipped filetypes" = "Yerel olarak atlanan dosya t├╝rlerini y├Ânet"
"Max Savings" = "Maksimum Tasarruf"
"Maximum Compression Threads" = "Maksimum S─▒k─▒┼şt─▒rma ─░┼ş Par├ğac─▒─ş─▒"
"Mode" = "Mod"
"Monitor compressed folders for changes" = "S─▒k─▒┼şt─▒r─▒lm─▒┼ş klas├Ârleri de─şi┼şiklikler i├ğin izle"
"Never" = "Asla"
"Next scheduled: {0:dd MMM yyyy} at {0:HH:mm:ss}" = "Sonraki zamanlanmış: {0:dd MMM yyyy} saat {0:HH:mm:ss}"
"No installed Steam games were found." = "Yüklü Steam oyunu bulunamadı."
"No wiki data" = "Wiki verisi yok"
"Not Compressed" = "S─▒k─▒┼şt─▒r─▒lmam─▒┼ş"
"Not enough space" = "Yeterli alan yok"
"On Schedule" = "Zamanlamaya G├Âre"
"On Schedule if system is also idle" = "Sistem bo┼şta ise zamanlamaya g├Âre"
"Open" = "A├ğ"
"Open Settings Folder" = "Ayarlar Klas├Âr├╝n├╝ A├ğ"
"Operation cancelled." = "İşlem iptal edildi."
"Operation failed: {0}" = "İşlem başarısız: {0}"
"Original Size" = "Orijinal Boyut"
"Paused" = "Duraklatıldı"
"Please check your internet connection and try again" = "L├╝tfen internet ba─şlant─▒n─▒z─▒ kontrol edip tekrar deneyin"
"Please wait until the current operation is finished" = "L├╝tfen mevcut i┼şlem bitene kadar bekleyin"
"Preparing" = "Hazırlanıyor"
"Quickly parses over files and estimates their compression ratio without writing to disk. This will likely be super laggy on HDDs!" = "Diske yazmadan dosyaları hızla tarar ve sıkıştırma oranını tahmin eder. HDD'lerde yavaş olabilir!"
"Re-analyse all watched folders" = "T├╝m izlenen klas├Ârleri yeniden analiz et"
"Re-analyse this folder" = "Bu klas├Âr├╝ yeniden analiz et"
"Recently Updated" = "Yakın Zamanda Güncellenenler"
"Recommended Action" = "Önerilen Eylem"
"Reload Languages.\nChecks online for updated language definitions" = "Dilleri Yenile.\nGüncel dil tanımlamaları için çevrimiçi kontrol eder"
"Reload Steam Library list" = "Steam Kütüphane listesini yenile"
"Remove from Watchlist" = "─░zleme Listesinden Kald─▒r"
"Reset" = "S─▒f─▒rla"
"Restart as Admin" = "Y├Ânetici Olarak Yeniden Ba┼şlat"
"SHOW QUEUE" = "SIRAYI GÖSTER"
"SKIPLIST SELECTION" = "ATLAMA LİSTESİ SEÇİMİ"
"Saved" = "Tasarruf Edildi"
"Savings" = "Tasarruf"
"Scanning installed Steam games..." = "Yüklü Steam oyunları taranıyor..."
"Search by game name or SteamID..." = "Oyun ad─▒ veya SteamID ile ara..."
"Select" = "Seç"
"Select a folder to compress" = "Sıkıştırılacak bir klasör seçin"
"Select all" = "Tümünü seç"
"Select all compressable" = "Sıkıştırılabilir olanları seç"
"Select all visible games" = "Görünür tüm oyunları seç"
"Settings" = "Ayarlar"
"Show notification on completion" = "Tamamland─▒─ş─▒nda bildirim g├Âster"
"Sort" = "Sırala"
"Sort By" = "S─▒ralama ├ûl├ğ├╝t├╝"
"Start CompactGUI in system tray" = "CompactGUI'yi sistem tepsisinde ba┼şlat"
"Status" = "Durum"
"Steam Library" = "Steam Kütüphanesi"
"SteamID" = "SteamID"
"Submit Results" = "Sonu├ğlar─▒ G├Ânder"
"Submitted to wiki" = "Wiki'ye g├Ânderildi"
"Success" = "Ba┼şar─▒l─▒"
"System Integration" = "Sistem Entegrasyonu"
"The SnackbarPresenter was never set" = "SnackbarPresenter ayarlanmad─▒"
"There is not enough free space on this drive to safely compress this folder. You need at least 50% of this folder's size free to ensure Windows does not cause issues." = "Bu klasörü güvenle sıkıştırmak için sürücüde yeterli boş alan yok. Windows'un sorun çıkarmaması için klasör boyutunun en az %50'si kadar boş alan gereklidir."
"This game uses DirectStorage technology. If you are using this feature, you should not compress this game." = "Bu oyun DirectStorage teknolojisini kullan─▒yor. E─şer bu ├Âzelli─şi kullan─▒yorsan─▒z, bu oyunu s─▒k─▒┼şt─▒rmamal─▒s─▒n─▒z."
"Total Results" = "Toplam Sonu├ğlar"
"UI Settings" = "Aray├╝z Ayarlar─▒"
"UID" = "UID"
"Uncompress" = "S─▒k─▒┼şt─▒rmay─▒ A├ğ"
"Uncompressed" = "Sıkıştırılmamış"
"Uncompressing..." = "Sıkıştırma açılıyor..."
"Unknown" = "Bilinmiyor"
"Update Available" = "Güncelleme Mevcut"
"Update Available ▸ Version {0}" = "Güncelleme Mevcut - Sürüm {0}"
"Update Settings" = "G├╝ncelleme Ayarlar─▒"
"Update in Steam" = "Steam'de Güncelle"
"Use exclusions" = "İstisnaları kullan"
"Use recommended mode" = "Önerilen modu kullan"
"Version" = "S├╝r├╝m"
"Waiting" = "Bekliyor"
"Watch folder for changes" = "Klas├Âr├╝ de─şi┼şiklikler i├ğin izle"
"Watched Folders" = "─░zlenen Klas├Ârler"
"Watcher" = "─░zleyici"
"WatcherPage" = "WatcherPage"
"When System is Idle" = "Sistem Bo┼ştayken"
"Working" = "├çal─▒┼ş─▒yor"
"XPRESS 16K" = "XPRESS 16K"
"XPRESS 4K" = "XPRESS 4K"
"XPRESS 8K" = "XPRESS 8K"
"Yes" = "Evet"
"You currently have {0} folders being watched. Closing CompactGUI will stop them from being monitored.{1}{1}Are you sure you want to exit?" = "Şu anda izlenen {0} klasörünüz var. CompactGUI'yi kapatmak izlenmelerini durduracaktır.{1}{1}Çıkmak istediğinize emin misiniz?"
"Your settings have been reset to their default to accommodate the update" = "Ayarlarınız güncellemeye uyum sağlamak için varsayılana sıfırlandı"
"Your settings have been reset to their default." = "Ayarlarınız varsayılana sıfırlandı."
"can be saved" = "tasarruf edilebilir"
"contained files" = "i├ğerilen dosyalar"
"day(s)" = "g├╝n"
"edit" = "d├╝zenle"
"edit skipped filetypes" = "atlanan dosya t├╝rlerini d├╝zenle"
"estimated savings" = "tahmini tasarruf"
"every" = "her"
"games" = "oyunlar"
"just now" = "az ├Ânce"
"last compressed:" = "son s─▒k─▒┼şt─▒r─▒lma:"
"last modified:" = "son de─şi┼ştirilme:"
"recommended" = "önerilen"
"saved" = "kaydedildi"
"select a folder" = "bir klas├Âr se├ğin"
"uncompressed size" = "s─▒k─▒┼şt─▒r─▒lmam─▒┼ş boyut"
"{0:0} days ago" = "{0:0} g├╝n ├Ânce"
"{0:0} hours ago" = "{0:0} saat ├Ânce"
"{0:0} minutes ago" = "{0:0} dakika ├Ânce"
"{0} saved" = "{0} tasarruf edildi"
"{0}% decayed" = "%{0} bozuldu"

[context."Background Scheduler"]
"CompactGUI is running a scheduled task and will compress monitored folders in the background" = "CompactGUI planlanmış bir görevi çalıştırıyor ve izlenen klasörleri arka planda sıkıştıracak"
"Next scheduled task is on {0}" = "Sonraki planlanmış görev: {0}"
"Scheduled Compression Completed" = "Planlanmış Sıkıştırma Tamamlandı"
"Scheduled Compression Running" = "Planlanmış Sıkıştırma Çalışıyor"

[context."Compression estimate"]
"unknown" = "bilinmiyor"

[context."Compression size"]
"After" = "Sonra"
"Before" = "├ûnce"

[context."File size"]
"B" = "B"
"EB" = "EB"
"GB" = "GB"
"KB" = "KB"
"MB" = "MB"
"PB" = "PB"
"TB" = "TB"

[context."Folder Compression Queue"]
"COMPLETED" = "TAMAMLANDI"
"Clear completed" = "Tamamlananları temizle"
"Expected savings" = "Beklenen tasarruf"
"PENDING" = "BEKLEYEN"
"Queue" = "Sıra"
"To process" = "İşlenecek"
"{0} of {1} completed" = "{1} işlemin {0} kadarı tamamlandı"

[context."Folder status"]
"Unknown" = "Bilinmiyor"

[context."Relative date"]
"Unknown" = "Bilinmiyor"

[context."Schedule"]
"at" = "saat"

[context."Skiplist aggression"]
"high" = "y├╝ksek"
"low" = "d├╝┼ş├╝k"
"medium" = "orta"

[context."Skiplist editor"]
"Save" = "Kaydet"

[context."Steam Library Compression Mode Button"]
"Compress | {0}" = "Sıkıştır | {0}"

[context."Steam Library Tab Headings"]
"CURRENT SIZE" = "MEVCUT BOYUT"
"GAME" = "OYUN"
"RECOMMENDED ACTION" = "ÖNERİLEN EYLEM"
"SAVINGS" = "TASARRUF"
"STATUS" = "DURUM"

[context."Storage savings"]
"saved" = "kaydedildi"
