# CompactGUI Localisation
# @version 2
# @programversion 4.0.0-beta.11

# ===================
# Translations

"Add" = "添加"
"Add a custom folder to the watchlist" = "添加自定义文件夹到监控列表"
"Add selected to queue" = "添加选中项到队列"
"Add to Compression Queue" = "添加到压缩队列"
"Add to compression queue" = "添加到压缩队列"
"Add to right-click context menu" = "添加到右键菜单"
"Add to start menu" = "添加到开始菜单"
"Added to Queue" = "已添加到队列"
"Admin" = "管理员权限"
"Aggression of online skiplist" = "在线跳过列表的激进程度"
"Always show details on Compression Mode buttons" = "始终在压缩模式按钮上显示详细信息"
"Analysing" = "正在分析"
"Analysing..." = "分析中……"
"Applied to all folders" = "已应用到所有文件夹"
"Ascending" = "递增"
"Awaiting Compression" = "等待压缩"
"Background Watcher Settings" = "后台监控设置"
"COMPARE METHODS" = "比较压缩模式"
"COMPRESSION MODE " = "压缩模式"
"Cancel" = "取消"
"Cancel Background Compressor" = "取消后台压缩"
"Cancel operation" = "取消操作"
"Cannot remove folder" = "无法移除文件夹"
"Check for pre-release updates" = "检查预发布更新"
"Choose Compression" = "选择压缩模式"
"Clear filters" = "清除筛选条件"
"Click to download" = "点击下载"
"CompactGUI" = "CompactGUI"
"Complete" = "完成"
"Compress" = "压缩"
"Compress Again" = "再次压缩"
"Compress All Now" = "立即全部压缩"
"Compress Selected" = "压缩选中项"
"Compress folders: " = "压缩文件夹："
"Compressed" = "已压缩"
"Compressing..." = "压缩中……"
"Compression" = "压缩模式"
"Compression DB" = "压缩数据库"
"Compression Settings" = "压缩设置"
"Compression Summary" = "压缩摘要"
"Compression options have been applied to all folders" = "压缩选项已应用到所有文件夹"
"Current Size" = "当前大小"
"Database Results" = "数据库结果"
"Descending" = "递减"
"Deselect all" = "取消全选"
"Direct Storage" = "Direct Storage"
"Do Not Compress" = "无需压缩"
"Do not compress" = "无需压缩"
"Drive unavailable" = "驱动器不可用"
"Edit list" = "编辑列表"
"Estimate Compression for non-Steam Folders (beta)" = "估算非 Steam 文件夹的压缩率 （测试版）"
"Estimated Size" = "预估大小"
"Estimated size" = "预估大小"
"Exit" = "退出"
"Extensions in this folder" = "此文件夹中包含的扩展名"
"Failed" = "失败"
"Failed to submit to wiki" = "提交到 Wiki 失败"
"Filetype Management" = "文件类型管理"
"Filter" = "筛选"
"Finishing {0} active file operations; do not power off." = "正在完成 {0} 个活跃的文件操作；请不要关闭软件。"
"For Steam Games, this uses the database to determine types to skip. For non-Steam folders this is based on the smart analyser." = "对于 Steam 游戏，将使用数据库确定要跳过的文件类型。对于非 Steam 文件夹，则由智能分析器决定。"
"For Steam games only.\nWhen choosing to skip user-submitted filetypes, this setting determines how many submissions are required for each filetype to consider skipping it. \n'low' is generally best, as higher options run the risk of skipping files that would otherwise compress well." = "仅适用于 Steam 游戏。\n在选择跳过用户提交的文件类型时，该设置决定了每种文件类型需要达到多少次提交才会考虑跳过。\n“低”通常是最佳选项，因为更高的选项有跳过原本能压缩得很好的文件的风险。"
"Game" = "游戏名"
"Game Name" = "游戏名称"
"Games" = "个游戏"
"Go to Database Results" = "查看数据库结果"
"HDDs only use 1 thread" = "机械硬盘仅使用 1 个线程"
"Home" = "主页"
"Include global skiplist" = "使用全局跳过列表"
"Include global skipped file types" = "使用全局跳过的文件类型"
"Include smart skiplist" = "使用智能跳过列表"
"Include smart skipped file types" = "使用智能跳过的文件类型"
"Insufficient permission to access this folder" = "没有足够的权限访问此文件夹"
"LZX" = "LZX"
"Last Fetched: {0:dd MMM yyyy HH:mm:ss}" = "上次获取： {0:yyyy年 M月 d日 HH:mm:ss}"
"Last analysed {0}" = "上次分析 {0}"
"Last ran: {0:dd MMM yyyy} at {0:HH:mm:ss}" = "上次运行： {0:yyyy年 M月 d日 HH:mm:ss}"
"Library location" = "库位置"
"Manage local skipped filetypes" = "管理本地跳过的文件类型"
"Max Savings" = "最大节省"
"Maximum Compression Threads" = "最大压缩线程数"
"Mode" = "压缩模式"
"Monitor compressed folders for changes" = "监控已压缩文件夹的更改"
"Never" = "从不"
"Next scheduled: {0:dd MMM yyyy} at {0:HH:mm:ss}" = "下次计划： {0:yyyy年 M月 d日 HH:mm:ss}"
"No installed Steam games were found." = "未发现已安装的 Steam 游戏。"
"No wiki data" = "无 wiki 数据"
"Not Compressed" = "未压缩"
"Not enough space" = "空间不足"
"On Schedule" = "按计划"
"On Schedule if system is also idle" = "按计划且系统空闲时"
"Open" = "打开"
"Open Settings Folder" = "打开设置文件夹"
"Operation cancelled." = "操作已取消。"
"Operation failed: {0}" = "操作失败： {0}"
"Original Size" = "原始大小"
"Paused" = "已暂停"
"Please check your internet connection and try again" = "请检查你的网络连接并重试"
"Please wait until the current operation is finished" = "请等待当前操作完成"
"Preparing" = "正在准备"
"Quickly parses over files and estimates their compression ratio without writing to disk. This will likely be super laggy on HDDs!" = "快速分析文件并估算压缩率而无需写入磁盘。这在机械硬盘上可能会非常卡顿！"
"Re-analyse all watched folders" = "重新分析所有受监控文件夹"
"Re-analyse this folder" = "重新分析此文件夹"
"Recently Updated" = "近期更新"
"Recommended Action" = "推荐操作"
"Reload Languages.\nChecks online for updated language definitions" = "重新加载语言。\n联网检查语言文件更新"
"Reload Steam Library list" = "重新加载 Steam 库列表"
"Remove from Watchlist" = "从监控列表中移除"
"Reset" = "重置"
"Restart as Admin" = "以管理员身份重新启动"
"SHOW QUEUE" = "展开队列"
"SKIPLIST SELECTION" = "跳过列表选择"
"Saved" = "已节省"
"Savings" = "节省"
"Scanning installed Steam games..." = "正在扫描已安装的 Steam 游戏……"
"Search by game name or SteamID..." = "按游戏名称或 SteamID 搜索……"
"Select" = "选择"
"Select a folder to compress" = "选择要压缩的文件夹"
"Select all" = "全选"
"Select all compressable" = "全选可压缩项"
"Select all visible games" = "全选可见游戏"
"Settings" = "设置"
"Show notification on completion" = "完成时显示通知"
"Sort" = "排序方式"
"Sort By" = "排序方式"
"Start CompactGUI in system tray" = "启动时最小化到系统托盘"
"Status" = "状态"
"Steam Library" = "Steam 库"
"SteamID" = "SteamID"
"Submit Results" = "提交结果"
"Submitted to wiki" = "已提交到 wiki"
"Success" = "成功"
"System Integration" = "系统集成"
"The SnackbarPresenter was never set" = "SnackbarPresenter 从未被设置"
"There is not enough free space on this drive to safely compress this folder. You need at least 50% of this folder's size free to ensure Windows does not cause issues." = "驱动器的可用空间不足以安全压缩此文件夹。你需要至少预留相当于此文件夹大小的 50% 的可用空间以确保 Windows 不会出现问题。"
"This game uses DirectStorage technology. If you are using this feature, you should not compress this game." = "此游戏使用 DirectStorage 技术。如果你正在使用此功能，则不应压缩此游戏。"
"Total Results" = "结果总数"
"UI Settings" = "UI 设置"
"UID" = "UID"
"Uncompress" = "解压缩"
"Uncompressed" = "未压缩"
"Uncompressing..." = "解压缩中……"
"Unknown" = "未知"
"Update Available" = "更新可用"
"Update Available ▸ Version {0}" = "更新可用 ▸ 版本 {0}"
"Update Settings" = "更新设置"
"Update in Steam" = "在 Steam 中更新"
"Use exclusions" = "使用跳过列表"
"Use recommended mode" = "使用推荐模式"
"Version" = "版本"
"Waiting" = "正在等待"
"Watch folder for changes" = "监控此文件夹的更改"
"Watched Folders" = "受监控文件夹"
"Watcher" = "监控"
"WatcherPage" = "监控页"
"When System is Idle" = "当系统空闲时"
"Working" = "正在处理"
"XPRESS 16K" = "XPRESS 16K"
"XPRESS 4K" = "XPRESS 4K"
"XPRESS 8K" = "XPRESS 8K"
"Yes" = "确定"
"You currently have {0} folders being watched. Closing CompactGUI will stop them from being monitored.{1}{1}Are you sure you want to exit?" = "你目前有 {0} 个文件夹正在被监控。关闭 CompactGUI 将停止对它们的监控。{1}{1}你确定要退出吗？"
"Your settings have been reset to their default to accommodate the update" = "你的设置已被重置以适应更新"
"Your settings have been reset to their default." = "你的设置已被重置"
"can be saved" = "可以节省"
"contained files" = "包含文件数"
"day(s)" = "天"
"edit" = "编辑"
"edit skipped filetypes" = "编辑跳过的文件类型"
"estimated savings" = "预估节省"
"every" = "每"
"games" = "个游戏"
"just now" = "刚刚"
"last compressed:" = "上次压缩："
"last modified:" = "上次修改："
"recommended" = "推荐"
"saved" = "已节省"
"select a folder" = "选择文件夹"
"uncompressed size" = "未压缩大小"
"{0:0} days ago" = "{0:0} 天前"
"{0:0} hours ago" = "{0:0} 小时前"
"{0:0} minutes ago" = "{0:0} 分钟前"
"{0} saved" = "{0} 已节省"
"{0}% decayed" = "{0}% 需重新压缩"

[context."Background Scheduler"]
"CompactGUI is running a scheduled task and will compress monitored folders in the background" = "CompactGUI正在运行一个计划任务并将会在后台压缩监控文件夹"
"Next scheduled task is on {0}" = "下一次计划压缩在 {0}"
"Scheduled Compression Completed" = "计划压缩已完成"
"Scheduled Compression Running" = "计划压缩运行中"

[context."Compression estimate"]
"unknown" = "未知"

[context."Compression size"]
"After" = "压缩后"
"Before" = "压缩前"

[context."File size"]
"B" = "B"
"EB" = "EB"
"GB" = "GB"
"KB" = "KB"
"MB" = "MB"
"PB" = "PB"
"TB" = "TB"

[context."Folder Compression Queue"]
"COMPLETED" = "已完成"
"Clear completed" = "清除已完成项"
"Expected savings" = "预期节省"
"PENDING" = "待压缩"
"Queue" = "队列"
"To process" = "待处理"
"{0} of {1} completed" = "{0} / {1} 已完成"

[context."Folder status"]
"Unknown" = "未知"

[context."Relative date"]
"Unknown" = "未知"

[context."Schedule"]
"at" = "在"

[context."Skiplist aggression"]
"high" = "高"
"low" = "低"
"medium" = "中"

[context."Skiplist editor"]
"Save" = "保存"

[context."Steam Library Compression Mode Button"]
"Compress | {0}" = "压缩 | {0}"

[context."Steam Library Tab Headings"]
"CURRENT SIZE" = "当前大小"
"GAME" = "游戏"
"RECOMMENDED ACTION" = "推荐操作"
"SAVINGS" = "节省"
"STATUS" = "状态"

[context."Storage savings"]
"saved" = "已节省"
