'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace i18n
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class i18n
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CompactGUI.i18n", GetType(i18n).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Public Shared ReadOnly Property _Set() As String
            Get
                Return ResourceManager.GetString("Set", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration.
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply to all.
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration_ApplyAll() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration_ApplyAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to files will be skipped.
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration_SkipFile() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration_SkipFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skip file types specified in settings.
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration_SkipFileTypes() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration_SkipFileTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skip file types likely to compress poorly.
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration_SkipFileTypesLikelyPoorly() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration_SkipFileTypesLikelyPoorly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For Steam Games:
        '''skips files based on database results
        '''
        '''For Non-Steam Folders:
        '''skips files based on compression estimate.
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration_SkipFileTypesLikelyPoorlyTip() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration_SkipFileTypesLikelyPoorlyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Watch folder for changes.
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration_WatchFolderChanges() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration_WatchFolderChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Results.
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Games.
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_Games() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_Games", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search by game name or SteamID....
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_SearchSteamID() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_SearchSteamID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort By.
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_Sort() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_Sort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ascending.
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_SortAscending() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_SortAscending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descending.
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_SortDescending() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_SortDescending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Name.
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_SortGameName() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_SortGameName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max Savings.
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_SortMaxSavings() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_SortMaxSavings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SteamID.
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_SortSteamID() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_SortSteamID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compression Mode.
        '''</summary>
        Public Shared ReadOnly Property CompressionMode() As String
            Get
                Return ResourceManager.GetString("CompressionMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LZX.
        '''</summary>
        Public Shared ReadOnly Property CompressionMode_LZX() As String
            Get
                Return ResourceManager.GetString("CompressionMode_LZX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to XPRESS 16K.
        '''</summary>
        Public Shared ReadOnly Property CompressionMode_XPRESS16K() As String
            Get
                Return ResourceManager.GetString("CompressionMode_XPRESS16K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to XPRESS 4K.
        '''</summary>
        Public Shared ReadOnly Property CompressionMode_XPRESS4K() As String
            Get
                Return ResourceManager.GetString("CompressionMode_XPRESS4K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to XPRESS 8K.
        '''</summary>
        Public Shared ReadOnly Property CompressionMode_XPRESS8K() As String
            Get
                Return ResourceManager.GetString("CompressionMode_XPRESS8K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estimated size.
        '''</summary>
        Public Shared ReadOnly Property CompressionModeRadio_EstimatedSize() As String
            Get
                Return ResourceManager.GetString("CompressionModeRadio_EstimatedSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Savings.
        '''</summary>
        Public Shared ReadOnly Property CompressionModeRadio_Savings() As String
            Get
                Return ResourceManager.GetString("CompressionModeRadio_Savings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TOTAL RESULTS.
        '''</summary>
        Public Shared ReadOnly Property CompressionModeRadio_TotalResults() As String
            Get
                Return ResourceManager.GetString("CompressionModeRadio_TotalResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to unknown.
        '''</summary>
        Public Shared ReadOnly Property CompressionModeRadio_Unknown() As String
            Get
                Return ResourceManager.GetString("CompressionModeRadio_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Folder to Queue.
        '''</summary>
        Public Shared ReadOnly Property Home_AddFolder() As String
            Get
                Return ResourceManager.GetString("Home_AddFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compress Again.
        '''</summary>
        Public Shared ReadOnly Property Home_CompressAgain() As String
            Get
                Return ResourceManager.GetString("Home_CompressAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compress Selected.
        '''</summary>
        Public Shared ReadOnly Property Home_CompressSelected() As String
            Get
                Return ResourceManager.GetString("Home_CompressSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select a folder.
        '''</summary>
        Public Shared ReadOnly Property Home_SelectFolder() As String
            Get
                Return ResourceManager.GetString("Home_SelectFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submit Results.
        '''</summary>
        Public Shared ReadOnly Property Home_SubmitResults() As String
            Get
                Return ResourceManager.GetString("Home_SubmitResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uncompress.
        '''</summary>
        Public Shared ReadOnly Property Home_Uncompress() As String
            Get
                Return ResourceManager.GetString("Home_Uncompress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version.
        '''</summary>
        Public Shared ReadOnly Property Home_Version() As String
            Get
                Return ResourceManager.GetString("Home_Version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome.
        '''</summary>
        Public Shared ReadOnly Property Message_Welcome() As String
            Get
                Return ResourceManager.GetString("Message_Welcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You currently have {0} folders being watched. Closing CompactGUI will stop them from being monitored.
        '''
        '''Are you sure you want to exit?.
        '''</summary>
        Public Shared ReadOnly Property MessageBox_ExitText() As String
            Get
                Return ResourceManager.GetString("MessageBox_ExitText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WatcherPage.
        '''</summary>
        Public Shared ReadOnly Property PageNameWatcher() As String
            Get
                Return ResourceManager.GetString("PageNameWatcher", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Background Watcher Settings.
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compress folders: .
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When System is Idle.
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders_Idle() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders_Idle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last ran: {0:dd MMM yyyy \a\t HH:mm:ss}.
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders_LastRanFormat() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders_LastRanFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Never.
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders_Never() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders_Never", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Next scheduled: {0:dd MMM yyyy \a\t HH:mm:ss}.
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders_NextScheduledFormat() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders_NextScheduledFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On Schedule.
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders_OnSchedule() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders_OnSchedule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On Schedule if system is also idle.
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders_OnScheduleIdle() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders_OnScheduleIdle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monitor compressed folders for changes.
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_FoldersChanges() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_FoldersChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to at.
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_Time_At() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_Time_At", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to day(s).
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_Time_Day() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_Time_Day", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to every.
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_Time_Every() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_Time_Every", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compression Settings.
        '''</summary>
        Public Shared ReadOnly Property SetCompression() As String
            Get
                Return ResourceManager.GetString("SetCompression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HDDs only use 1 thread.
        '''</summary>
        Public Shared ReadOnly Property SetCompression_HDDThread() As String
            Get
                Return ResourceManager.GetString("SetCompression_HDDThread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum Compression Threads.
        '''</summary>
        Public Shared ReadOnly Property SetCompression_MaxThreads() As String
            Get
                Return ResourceManager.GetString("SetCompression_MaxThreads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estimate Compression for non-Steam Folders (beta).
        '''</summary>
        Public Shared ReadOnly Property SetCompression_NonSteamFolders() As String
            Get
                Return ResourceManager.GetString("SetCompression_NonSteamFolders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filetype Management.
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manage local skipped filetypes.
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_LocalSkipFiletypes() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_LocalSkipFiletypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to edit skipped filetypes.
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_LocalSkipFiletypesEdit() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_LocalSkipFiletypesEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agression of online skiplist.
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_OnlineSkiplistAgression() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_OnlineSkiplistAgression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to high.
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_OnlineSkiplistAgressionHigh() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_OnlineSkiplistAgressionHigh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to low.
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_OnlineSkiplistAgressionLow() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_OnlineSkiplistAgressionLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to medium.
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_OnlineSkiplistAgressionMedium() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_OnlineSkiplistAgressionMedium", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For Steam games only.
        '''When choosing to skip user-submitted filetypes, this setting determines how many submissions are required for each filetype to consider skipping it. 
        '''&apos;low&apos; is generally best, as higher options run the risk of skipping files that would otherwise compress well..
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_OnlineSkiplistAgressionTip() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_OnlineSkiplistAgressionTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Settings Folder.
        '''</summary>
        Public Shared ReadOnly Property SetOpenSettingsFolder() As String
            Get
                Return ResourceManager.GetString("SetOpenSettingsFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System Integration.
        '''</summary>
        Public Shared ReadOnly Property SetSystemIntegration() As String
            Get
                Return ResourceManager.GetString("SetSystemIntegration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show notification on completion.
        '''</summary>
        Public Shared ReadOnly Property SetSystemIntegration_CompletionNotification() As String
            Get
                Return ResourceManager.GetString("SetSystemIntegration_CompletionNotification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add to right-click context menu.
        '''</summary>
        Public Shared ReadOnly Property SetSystemIntegration_RightClickMenu() As String
            Get
                Return ResourceManager.GetString("SetSystemIntegration_RightClickMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add to start menu.
        '''</summary>
        Public Shared ReadOnly Property SetSystemIntegration_StartMenu() As String
            Get
                Return ResourceManager.GetString("SetSystemIntegration_StartMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start CompactGUI in system tray.
        '''</summary>
        Public Shared ReadOnly Property SetSystemIntegration_Startup() As String
            Get
                Return ResourceManager.GetString("SetSystemIntegration_Startup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UI Settings.
        '''</summary>
        Public Shared ReadOnly Property SetUi() As String
            Get
                Return ResourceManager.GetString("SetUi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Always show details on Compression Mode buttons.
        '''</summary>
        Public Shared ReadOnly Property SetUi_CompressionDetails() As String
            Get
                Return ResourceManager.GetString("SetUi_CompressionDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language (Requires Restart).
        '''</summary>
        Public Shared ReadOnly Property SetUi_LanguageChanged() As String
            Get
                Return ResourceManager.GetString("SetUi_LanguageChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language changed successfully. You may need to restart the application for all changes to take effect..
        '''</summary>
        Public Shared ReadOnly Property SetUi_LanguageChangedMsg() As String
            Get
                Return ResourceManager.GetString("SetUi_LanguageChangedMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language Changed.
        '''</summary>
        Public Shared ReadOnly Property SetUi_LanguageChangedTitle() As String
            Get
                Return ResourceManager.GetString("SetUi_LanguageChangedTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Settings.
        '''</summary>
        Public Shared ReadOnly Property SetUpdate() As String
            Get
                Return ResourceManager.GetString("SetUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check for pre-release updates.
        '''</summary>
        Public Shared ReadOnly Property SetUpdate_CheckPreUpdates() As String
            Get
                Return ResourceManager.GetString("SetUpdate_CheckPreUpdates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to B.
        '''</summary>
        Public Shared ReadOnly Property SizeUnit_B() As String
            Get
                Return ResourceManager.GetString("SizeUnit_B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EB.
        '''</summary>
        Public Shared ReadOnly Property SizeUnit_EB() As String
            Get
                Return ResourceManager.GetString("SizeUnit_EB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GB.
        '''</summary>
        Public Shared ReadOnly Property SizeUnit_GB() As String
            Get
                Return ResourceManager.GetString("SizeUnit_GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to KB.
        '''</summary>
        Public Shared ReadOnly Property SizeUnit_KB() As String
            Get
                Return ResourceManager.GetString("SizeUnit_KB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MB.
        '''</summary>
        Public Shared ReadOnly Property SizeUnit_MB() As String
            Get
                Return ResourceManager.GetString("SizeUnit_MB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PB.
        '''</summary>
        Public Shared ReadOnly Property SizeUnit_PB() As String
            Get
                Return ResourceManager.GetString("SizeUnit_PB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TB.
        '''</summary>
        Public Shared ReadOnly Property SizeUnit_TB() As String
            Get
                Return ResourceManager.GetString("SizeUnit_TB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Applied to all folders.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_AppliedAllFolders() As String
            Get
                Return ResourceManager.GetString("SnackBar_AppliedAllFolders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compression options have been applied to all folders.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_AppliedAllFoldersTip() As String
            Get
                Return ResourceManager.GetString("SnackBar_AppliedAllFoldersTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot remove folder.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_CannotRemoveFolder() As String
            Get
                Return ResourceManager.GetString("SnackBar_CannotRemoveFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please wait until the current operation is finished.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_CannotRemoveFolderTip() As String
            Get
                Return ResourceManager.GetString("SnackBar_CannotRemoveFolderTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This game uses DirectStorage technology. If you are using this feature, you should not compress this game..
        '''</summary>
        Public Shared ReadOnly Property SnackBar_DirectStorageTechnology() As String
            Get
                Return ResourceManager.GetString("SnackBar_DirectStorageTechnology", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restart as Admin.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_RestartAdmin() As String
            Get
                Return ResourceManager.GetString("SnackBar_RestartAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insufficient permission to access this folder.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_RestartAdminTip() As String
            Get
                Return ResourceManager.GetString("SnackBar_RestartAdminTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The SnackbarPresenter was never set.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SnackbarPresenter() As String
            Get
                Return ResourceManager.GetString("SnackBar_SnackbarPresenter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compression.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWiki_Compression() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWiki_Compression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWiki_Game() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWiki_Game", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SteamID.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWiki_SteamID() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWiki_SteamID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UID.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWiki_UID() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWiki_UID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to submit to wiki.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWikiFailed() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWikiFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please check your internet connection and try again.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWikiFailedTip() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWikiFailedTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submitted to wiki.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWikiTitle() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWikiTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Success.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_Success() As String
            Get
                Return ResourceManager.GetString("SnackBar_Success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Added to Queue.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SuccessTip() As String
            Get
                Return ResourceManager.GetString("SnackBar_SuccessTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Available ▸ Version {0}.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_UpdateAvailable() As String
            Get
                Return ResourceManager.GetString("SnackBar_UpdateAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to download.
        '''</summary>
        Public Shared ReadOnly Property SnackBar_UpdateDownload() As String
            Get
                Return ResourceManager.GetString("SnackBar_UpdateDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to After.
        '''</summary>
        Public Shared ReadOnly Property Status_After() As String
            Get
                Return ResourceManager.GetString("Status_After", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Analysing.
        '''</summary>
        Public Shared ReadOnly Property Status_Analysing() As String
            Get
                Return ResourceManager.GetString("Status_Analysing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Awaiting Compression.
        '''</summary>
        Public Shared ReadOnly Property Status_AwaitingCompression() As String
            Get
                Return ResourceManager.GetString("Status_AwaitingCompression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Before.
        '''</summary>
        Public Shared ReadOnly Property Status_Before() As String
            Get
                Return ResourceManager.GetString("Status_Before", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compressed.
        '''</summary>
        Public Shared ReadOnly Property Status_Compressed() As String
            Get
                Return ResourceManager.GetString("Status_Compressed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compression Mode.
        '''</summary>
        Public Shared ReadOnly Property Status_CompressionMode() As String
            Get
                Return ResourceManager.GetString("Status_CompressionMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compression Summary.
        '''</summary>
        Public Shared ReadOnly Property Status_CompressionSummary() As String
            Get
                Return ResourceManager.GetString("Status_CompressionSummary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to contained files.
        '''</summary>
        Public Shared ReadOnly Property Status_ContainedFiles() As String
            Get
                Return ResourceManager.GetString("Status_ContainedFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Files Compressed.
        '''</summary>
        Public Shared ReadOnly Property Status_FilesCompressed() As String
            Get
                Return ResourceManager.GetString("Status_FilesCompressed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Fetched: {0:dd MMM yyyy HH:mm:ss}.
        '''</summary>
        Public Shared ReadOnly Property Status_LastFetched() As String
            Get
                Return ResourceManager.GetString("Status_LastFetched", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Compressed.
        '''</summary>
        Public Shared ReadOnly Property Status_NotCompressed() As String
            Get
                Return ResourceManager.GetString("Status_NotCompressed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Results State.
        '''</summary>
        Public Shared ReadOnly Property Status_ResultsState() As String
            Get
                Return ResourceManager.GetString("Status_ResultsState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Space Saved.
        '''</summary>
        Public Shared ReadOnly Property Status_SpaceSaved() As String
            Get
                Return ResourceManager.GetString("Status_SpaceSaved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to uncompressed size.
        '''</summary>
        Public Shared ReadOnly Property Status_UncompressedSize() As String
            Get
                Return ResourceManager.GetString("Status_UncompressedSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown.
        '''</summary>
        Public Shared ReadOnly Property Status_Unknown() As String
            Get
                Return ResourceManager.GetString("Status_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Working.
        '''</summary>
        Public Shared ReadOnly Property Status_Working() As String
            Get
                Return ResourceManager.GetString("Status_Working", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0:0} days ago.
        '''</summary>
        Public Shared ReadOnly Property Time_DaysAgo() As String
            Get
                Return ResourceManager.GetString("Time_DaysAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0:0} hours ago.
        '''</summary>
        Public Shared ReadOnly Property Time_HoursAgo() As String
            Get
                Return ResourceManager.GetString("Time_HoursAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0:0} minutes ago.
        '''</summary>
        Public Shared ReadOnly Property Time_MinutesAgo() As String
            Get
                Return ResourceManager.GetString("Time_MinutesAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to just now.
        '''</summary>
        Public Shared ReadOnly Property Time_Now() As String
            Get
                Return ResourceManager.GetString("Time_Now", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown.
        '''</summary>
        Public Shared ReadOnly Property Time_Unknown() As String
            Get
                Return ResourceManager.GetString("Time_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CompactGUI.
        '''</summary>
        Public Shared ReadOnly Property Title_CompactGUI() As String
            Get
                Return ResourceManager.GetString("Title_CompactGUI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compression DB.
        '''</summary>
        Public Shared ReadOnly Property Title_CompressionDB() As String
            Get
                Return ResourceManager.GetString("Title_CompressionDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Home.
        '''</summary>
        Public Shared ReadOnly Property Title_Home() As String
            Get
                Return ResourceManager.GetString("Title_Home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Watcher.
        '''</summary>
        Public Shared ReadOnly Property Title_Watcher() As String
            Get
                Return ResourceManager.GetString("Title_Watcher", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Public Shared ReadOnly Property UniAdd() As String
            Get
                Return ResourceManager.GetString("UniAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Admin.
        '''</summary>
        Public Shared ReadOnly Property UniAdmin() As String
            Get
                Return ResourceManager.GetString("UniAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Public Shared ReadOnly Property UniCancel() As String
            Get
                Return ResourceManager.GetString("UniCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to edit.
        '''</summary>
        Public Shared ReadOnly Property UniEdit() As String
            Get
                Return ResourceManager.GetString("UniEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Public Shared ReadOnly Property UniExit() As String
            Get
                Return ResourceManager.GetString("UniExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Public Shared ReadOnly Property UniOpen() As String
            Get
                Return ResourceManager.GetString("UniOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset.
        '''</summary>
        Public Shared ReadOnly Property UniReset() As String
            Get
                Return ResourceManager.GetString("UniReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Public Shared ReadOnly Property UniSave() As String
            Get
                Return ResourceManager.GetString("UniSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Public Shared ReadOnly Property UniYes() As String
            Get
                Return ResourceManager.GetString("UniYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add to compression queue.
        '''</summary>
        Public Shared ReadOnly Property Watcher_AddQueue() As String
            Get
                Return ResourceManager.GetString("Watcher_AddQueue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add a custom folder to the watchlist.
        '''</summary>
        Public Shared ReadOnly Property Watcher_AddTip() As String
            Get
                Return ResourceManager.GetString("Watcher_AddTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel Background Compressor.
        '''</summary>
        Public Shared ReadOnly Property Watcher_CancelBackgroundCompressor() As String
            Get
                Return ResourceManager.GetString("Watcher_CancelBackgroundCompressor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compress All Now.
        '''</summary>
        Public Shared ReadOnly Property Watcher_CompressAllNow() As String
            Get
                Return ResourceManager.GetString("Watcher_CompressAllNow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last analysed.
        '''</summary>
        Public Shared ReadOnly Property Watcher_LastAnalysed() As String
            Get
                Return ResourceManager.GetString("Watcher_LastAnalysed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to last compressed:.
        '''</summary>
        Public Shared ReadOnly Property Watcher_LastCompressed() As String
            Get
                Return ResourceManager.GetString("Watcher_LastCompressed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to last modified:.
        '''</summary>
        Public Shared ReadOnly Property Watcher_LastModified() As String
            Get
                Return ResourceManager.GetString("Watcher_LastModified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re-analyse all watched folders.
        '''</summary>
        Public Shared ReadOnly Property Watcher_ReAnalyse() As String
            Get
                Return ResourceManager.GetString("Watcher_ReAnalyse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re-analyse this folder.
        '''</summary>
        Public Shared ReadOnly Property Watcher_ReAnalyseFolder() As String
            Get
                Return ResourceManager.GetString("Watcher_ReAnalyseFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove from Watchlist.
        '''</summary>
        Public Shared ReadOnly Property Watcher_RemoveWatchlist() As String
            Get
                Return ResourceManager.GetString("Watcher_RemoveWatchlist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to decayed.
        '''</summary>
        Public Shared ReadOnly Property Watcher_WatchedDecayed() As String
            Get
                Return ResourceManager.GetString("Watcher_WatchedDecayed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Watched Folders.
        '''</summary>
        Public Shared ReadOnly Property Watcher_WatchedFolders() As String
            Get
                Return ResourceManager.GetString("Watcher_WatchedFolders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to saved.
        '''</summary>
        Public Shared ReadOnly Property Watcher_WatchedSaved() As String
            Get
                Return ResourceManager.GetString("Watcher_WatchedSaved", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
