'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace i18n
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class i18n
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CompactGUI.i18n", GetType(i18n).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property _Set() As String
            Get
                Return ResourceManager.GetString("Set", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Configuration 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Apply to all 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration_ApplyAll() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration_ApplyAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 files will be skipped 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration_SkipFile() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration_SkipFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Skip file types specified in settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration_SkipFileTypes() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration_SkipFileTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Skip file types likely to compress poorly 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration_SkipFileTypesLikelyPoorly() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration_SkipFileTypesLikelyPoorly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 For Steam Games:
        '''skips files based on database results
        '''
        '''For Non-Steam Folders:
        '''skips files based on compression estimate 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration_SkipFileTypesLikelyPoorlyTip() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration_SkipFileTypesLikelyPoorlyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Watch folder for changes 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionConfiguration_WatchFolderChanges() As String
            Get
                Return ResourceManager.GetString("CompressionConfiguration_WatchFolderChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Database Results 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Games 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_Games() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_Games", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Search by game name or SteamID... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_SearchSteamID() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_SearchSteamID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Sort By 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_Sort() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_Sort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Ascending 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_SortAscending() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_SortAscending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Descending 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_SortDescending() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_SortDescending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Game Name 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_SortGameName() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_SortGameName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Max Savings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_SortMaxSavings() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_SortMaxSavings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SteamID 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionDB_DatabaseResults_SortSteamID() As String
            Get
                Return ResourceManager.GetString("CompressionDB_DatabaseResults_SortSteamID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compression Mode 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionMode() As String
            Get
                Return ResourceManager.GetString("CompressionMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LZX 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionMode_LZX() As String
            Get
                Return ResourceManager.GetString("CompressionMode_LZX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 XPRESS 16K 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionMode_XPRESS16K() As String
            Get
                Return ResourceManager.GetString("CompressionMode_XPRESS16K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 XPRESS 4K 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionMode_XPRESS4K() As String
            Get
                Return ResourceManager.GetString("CompressionMode_XPRESS4K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 XPRESS 8K 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionMode_XPRESS8K() As String
            Get
                Return ResourceManager.GetString("CompressionMode_XPRESS8K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Estimated size 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionModeRadio_EstimatedSize() As String
            Get
                Return ResourceManager.GetString("CompressionModeRadio_EstimatedSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Savings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionModeRadio_Savings() As String
            Get
                Return ResourceManager.GetString("CompressionModeRadio_Savings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 TOTAL RESULTS 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionModeRadio_TotalResults() As String
            Get
                Return ResourceManager.GetString("CompressionModeRadio_TotalResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 unknown 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionModeRadio_Unknown() As String
            Get
                Return ResourceManager.GetString("CompressionModeRadio_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add Folder to Queue 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Home_AddFolder() As String
            Get
                Return ResourceManager.GetString("Home_AddFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compress Again 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Home_CompressAgain() As String
            Get
                Return ResourceManager.GetString("Home_CompressAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compress Selected 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Home_CompressSelected() As String
            Get
                Return ResourceManager.GetString("Home_CompressSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 select a folder 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Home_SelectFolder() As String
            Get
                Return ResourceManager.GetString("Home_SelectFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Submit Results 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Home_SubmitResults() As String
            Get
                Return ResourceManager.GetString("Home_SubmitResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Uncompress 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Home_Uncompress() As String
            Get
                Return ResourceManager.GetString("Home_Uncompress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Welcome 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Message_Welcome() As String
            Get
                Return ResourceManager.GetString("Message_Welcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 You currently have {0} folders being watched. Closing CompactGUI will stop them from being monitored.
        '''
        '''Are you sure you want to exit? 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property MessageBox_ExitText() As String
            Get
                Return ResourceManager.GetString("MessageBox_ExitText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 WatcherPage 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PageNameWatcher() As String
            Get
                Return ResourceManager.GetString("PageNameWatcher", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Background Watcher Settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compress folders:  的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 When System is Idle 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders_Idle() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders_Idle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Last ran: {0:dd MMM yyyy \a\t HH:mm:ss} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders_LastRanFormat() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders_LastRanFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Never 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders_Never() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders_Never", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Next scheduled: {0:dd MMM yyyy \a\t HH:mm:ss} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders_NextScheduledFormat() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders_NextScheduledFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 On Schedule 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders_OnSchedule() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders_OnSchedule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 On Schedule if system is also idle 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_CompressFolders_OnScheduleIdle() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_CompressFolders_OnScheduleIdle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Monitor compressed folders for changes 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_FoldersChanges() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_FoldersChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 at 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_Time_At() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_Time_At", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 day(s) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_Time_Day() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_Time_Day", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 every 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetBackgroundWatch_Time_Every() As String
            Get
                Return ResourceManager.GetString("SetBackgroundWatch_Time_Every", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compression Settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetCompression() As String
            Get
                Return ResourceManager.GetString("SetCompression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 HDDs only use 1 thread 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetCompression_HDDThread() As String
            Get
                Return ResourceManager.GetString("SetCompression_HDDThread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Maximum Compression Threads 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetCompression_MaxThreads() As String
            Get
                Return ResourceManager.GetString("SetCompression_MaxThreads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Estimate Compression for non-Steam Folders (beta) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetCompression_NonSteamFolders() As String
            Get
                Return ResourceManager.GetString("SetCompression_NonSteamFolders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Filetype Management 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Manage local skipped filetypes 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_LocalSkipFiletypes() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_LocalSkipFiletypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 edit skipped filetypes 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_LocalSkipFiletypesEdit() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_LocalSkipFiletypesEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Agression of online skiplist 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_OnlineSkiplistAgression() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_OnlineSkiplistAgression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 high 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_OnlineSkiplistAgressionHigh() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_OnlineSkiplistAgressionHigh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 low 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_OnlineSkiplistAgressionLow() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_OnlineSkiplistAgressionLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 medium 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_OnlineSkiplistAgressionMedium() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_OnlineSkiplistAgressionMedium", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 For Steam games only.
        '''When choosing to skip user-submitted filetypes, this setting determines how many submissions are required for each filetype to consider skipping it. 
        '''&apos;low&apos; is generally best, as higher options run the risk of skipping files that would otherwise compress well. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetFiletypeManagement_OnlineSkiplistAgressionTip() As String
            Get
                Return ResourceManager.GetString("SetFiletypeManagement_OnlineSkiplistAgressionTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 System Integration 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetSystemIntegration() As String
            Get
                Return ResourceManager.GetString("SetSystemIntegration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Show notification on completion 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetSystemIntegration_CompletionNotification() As String
            Get
                Return ResourceManager.GetString("SetSystemIntegration_CompletionNotification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add to right-click context menu 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetSystemIntegration_RightClickMenu() As String
            Get
                Return ResourceManager.GetString("SetSystemIntegration_RightClickMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add to start menu 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetSystemIntegration_StartMenu() As String
            Get
                Return ResourceManager.GetString("SetSystemIntegration_StartMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Start CompactGUI in system tray 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetSystemIntegration_Startup() As String
            Get
                Return ResourceManager.GetString("SetSystemIntegration_Startup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 UI Settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetUi() As String
            Get
                Return ResourceManager.GetString("SetUi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Always show details on Compression Mode buttons 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetUi_CompressionDetails() As String
            Get
                Return ResourceManager.GetString("SetUi_CompressionDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Language (Requires Restart) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetUi_LanguageChanged() As String
            Get
                Return ResourceManager.GetString("SetUi_LanguageChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Language changed successfully. You may need to restart the application for all changes to take effect. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetUi_LanguageChangedMsg() As String
            Get
                Return ResourceManager.GetString("SetUi_LanguageChangedMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Language Changed 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetUi_LanguageChangedTitle() As String
            Get
                Return ResourceManager.GetString("SetUi_LanguageChangedTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Update Settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetUpdate() As String
            Get
                Return ResourceManager.GetString("SetUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Check for pre-release updates 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SetUpdate_CheckPreUpdates() As String
            Get
                Return ResourceManager.GetString("SetUpdate_CheckPreUpdates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Applied to all folders 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_AppliedAllFolders() As String
            Get
                Return ResourceManager.GetString("SnackBar_AppliedAllFolders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compression options have been applied to all folders 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_AppliedAllFoldersTip() As String
            Get
                Return ResourceManager.GetString("SnackBar_AppliedAllFoldersTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cannot remove folder 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_CannotRemoveFolder() As String
            Get
                Return ResourceManager.GetString("SnackBar_CannotRemoveFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Please wait until the current operation is finished 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_CannotRemoveFolderTip() As String
            Get
                Return ResourceManager.GetString("SnackBar_CannotRemoveFolderTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 This game uses DirectStorage technology. If you are using this feature, you should not compress this game. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_DirectStorageTechnology() As String
            Get
                Return ResourceManager.GetString("SnackBar_DirectStorageTechnology", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Restart as Admin 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_RestartAdmin() As String
            Get
                Return ResourceManager.GetString("SnackBar_RestartAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Insufficient permission to access this folder 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_RestartAdminTip() As String
            Get
                Return ResourceManager.GetString("SnackBar_RestartAdminTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 The SnackbarPresenter was never set 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SnackbarPresenter() As String
            Get
                Return ResourceManager.GetString("SnackBar_SnackbarPresenter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compression 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWiki_Compression() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWiki_Compression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Game 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWiki_Game() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWiki_Game", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SteamID 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWiki_SteamID() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWiki_SteamID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 UID 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWiki_UID() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWiki_UID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to submit to wiki 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWikiFailed() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWikiFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Please check your internet connection and try again 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWikiFailedTip() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWikiFailedTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Submitted to wiki 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SubmitWikiTitle() As String
            Get
                Return ResourceManager.GetString("SnackBar_SubmitWikiTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Success 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_Success() As String
            Get
                Return ResourceManager.GetString("SnackBar_Success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Added to Queue 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_SuccessTip() As String
            Get
                Return ResourceManager.GetString("SnackBar_SuccessTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Update Available ▸ Version {0} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_UpdateAvailable() As String
            Get
                Return ResourceManager.GetString("SnackBar_UpdateAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Click to download 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SnackBar_UpdateDownload() As String
            Get
                Return ResourceManager.GetString("SnackBar_UpdateDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 After 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_After() As String
            Get
                Return ResourceManager.GetString("Status_After", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Analysing 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_Analysing() As String
            Get
                Return ResourceManager.GetString("Status_Analysing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Awaiting Compression 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_AwaitingCompression() As String
            Get
                Return ResourceManager.GetString("Status_AwaitingCompression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Before 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_Before() As String
            Get
                Return ResourceManager.GetString("Status_Before", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compressed 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_Compressed() As String
            Get
                Return ResourceManager.GetString("Status_Compressed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compression Mode 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_CompressionMode() As String
            Get
                Return ResourceManager.GetString("Status_CompressionMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compression Summary 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_CompressionSummary() As String
            Get
                Return ResourceManager.GetString("Status_CompressionSummary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 contained files 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_ContainedFiles() As String
            Get
                Return ResourceManager.GetString("Status_ContainedFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Files Compressed 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_FilesCompressed() As String
            Get
                Return ResourceManager.GetString("Status_FilesCompressed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Last Fetched: {0:dd MMM yyyy HH:mm:ss} 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_LastFetched() As String
            Get
                Return ResourceManager.GetString("Status_LastFetched", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Not Compressed 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_NotCompressed() As String
            Get
                Return ResourceManager.GetString("Status_NotCompressed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Results State 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_ResultsState() As String
            Get
                Return ResourceManager.GetString("Status_ResultsState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Space Saved 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_SpaceSaved() As String
            Get
                Return ResourceManager.GetString("Status_SpaceSaved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 uncompressed size 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_UncompressedSize() As String
            Get
                Return ResourceManager.GetString("Status_UncompressedSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Unknown 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_Unknown() As String
            Get
                Return ResourceManager.GetString("Status_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Working 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Status_Working() As String
            Get
                Return ResourceManager.GetString("Status_Working", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0:0} days ago 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Time_DaysAgo() As String
            Get
                Return ResourceManager.GetString("Time_DaysAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0:0} hours ago 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Time_HoursAgo() As String
            Get
                Return ResourceManager.GetString("Time_HoursAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0:0} minutes ago 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Time_MinutesAgo() As String
            Get
                Return ResourceManager.GetString("Time_MinutesAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 just now 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Time_Now() As String
            Get
                Return ResourceManager.GetString("Time_Now", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Unknown 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Time_Unknown() As String
            Get
                Return ResourceManager.GetString("Time_Unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 CompactGUI 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Title_CompactGUI() As String
            Get
                Return ResourceManager.GetString("Title_CompactGUI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compression DB 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Title_CompressionDB() As String
            Get
                Return ResourceManager.GetString("Title_CompressionDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Home 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Title_Home() As String
            Get
                Return ResourceManager.GetString("Title_Home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Watcher 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Title_Watcher() As String
            Get
                Return ResourceManager.GetString("Title_Watcher", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property UniAdd() As String
            Get
                Return ResourceManager.GetString("UniAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Admin 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property UniAdmin() As String
            Get
                Return ResourceManager.GetString("UniAdmin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cancel 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property UniCancel() As String
            Get
                Return ResourceManager.GetString("UniCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 edit 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property UniEdit() As String
            Get
                Return ResourceManager.GetString("UniEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Exit 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property UniExit() As String
            Get
                Return ResourceManager.GetString("UniExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Open 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property UniOpen() As String
            Get
                Return ResourceManager.GetString("UniOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Reset 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property UniReset() As String
            Get
                Return ResourceManager.GetString("UniReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Save 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property UniSave() As String
            Get
                Return ResourceManager.GetString("UniSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Yes 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property UniYes() As String
            Get
                Return ResourceManager.GetString("UniYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add to compression queue 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Watcher_AddQueue() As String
            Get
                Return ResourceManager.GetString("Watcher_AddQueue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add a custom folder to the watchlist 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Watcher_AddTip() As String
            Get
                Return ResourceManager.GetString("Watcher_AddTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cancel Background Compressor 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Watcher_CancelBackgroundCompressor() As String
            Get
                Return ResourceManager.GetString("Watcher_CancelBackgroundCompressor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compress All Now 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Watcher_CompressAllNow() As String
            Get
                Return ResourceManager.GetString("Watcher_CompressAllNow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Last analysed 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Watcher_LastAnalysed() As String
            Get
                Return ResourceManager.GetString("Watcher_LastAnalysed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 last compressed: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Watcher_LastCompressed() As String
            Get
                Return ResourceManager.GetString("Watcher_LastCompressed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 last modified: 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Watcher_LastModified() As String
            Get
                Return ResourceManager.GetString("Watcher_LastModified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Re-analyse all watched folders 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Watcher_ReAnalyse() As String
            Get
                Return ResourceManager.GetString("Watcher_ReAnalyse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Re-analyse this folder 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Watcher_ReAnalyseFolder() As String
            Get
                Return ResourceManager.GetString("Watcher_ReAnalyseFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Remove from Watchlist 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Watcher_RemoveWatchlist() As String
            Get
                Return ResourceManager.GetString("Watcher_RemoveWatchlist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 decayed 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Watcher_WatchedDecayed() As String
            Get
                Return ResourceManager.GetString("Watcher_WatchedDecayed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Watched Folders 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Watcher_WatchedFolders() As String
            Get
                Return ResourceManager.GetString("Watcher_WatchedFolders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 saved 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property Watcher_WatchedSaved() As String
            Get
                Return ResourceManager.GetString("Watcher_WatchedSaved", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
