'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace i18n
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class i18n
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CompactGUI.i18n", GetType(i18n).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Estimated size 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionModeRadioEstimatedSize() As String
            Get
                Return ResourceManager.GetString("CompressionModeRadioEstimatedSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Savings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionModeRadioSavings() As String
            Get
                Return ResourceManager.GetString("CompressionModeRadioSavings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 unknown 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property CompressionModeRadioUnknown() As String
            Get
                Return ResourceManager.GetString("CompressionModeRadioUnknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Ascending 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DatabasePage_Ascending() As String
            Get
                Return ResourceManager.GetString("DatabasePage_Ascending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Descending 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DatabasePage_Descending() As String
            Get
                Return ResourceManager.GetString("DatabasePage_Descending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 AFTER 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DatabasePageAFTER() As String
            Get
                Return ResourceManager.GetString("DatabasePageAFTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 BEFORE 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DatabasePageBEFORE() As String
            Get
                Return ResourceManager.GetString("DatabasePageBEFORE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 MODE 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DatabasePageMODE() As String
            Get
                Return ResourceManager.GetString("DatabasePageMODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SAVINGS 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DatabasePageSAVINGS() As String
            Get
                Return ResourceManager.GetString("DatabasePageSAVINGS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 TOTAL RESULTS 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DatabasePageTOTALRESULTS() As String
            Get
                Return ResourceManager.GetString("DatabasePageTOTALRESULTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Games 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DatabaseResultsGames() As String
            Get
                Return ResourceManager.GetString("DatabaseResultsGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Search by game name or SteamID... 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DatabaseResultsSearchSteamID() As String
            Get
                Return ResourceManager.GetString("DatabaseResultsSearchSteamID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Sort By 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DatabaseResultsSort() As String
            Get
                Return ResourceManager.GetString("DatabaseResultsSort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Game Name 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DatabaseResultsSortGameName() As String
            Get
                Return ResourceManager.GetString("DatabaseResultsSortGameName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Max Savings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DatabaseResultsSortMaxSavings() As String
            Get
                Return ResourceManager.GetString("DatabaseResultsSortMaxSavings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SteamID 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property DatabaseResultsSortSteamID() As String
            Get
                Return ResourceManager.GetString("DatabaseResultsSortSteamID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 contained files 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property FolderViewContainedFiles() As String
            Get
                Return ResourceManager.GetString("FolderViewContainedFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 uncompressed size 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property FolderViewUncompressedSize() As String
            Get
                Return ResourceManager.GetString("FolderViewUncompressedSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cancel Background Compressor 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property FolderWatcherCardCancelBackgroundCompressor() As String
            Get
                Return ResourceManager.GetString("FolderWatcherCardCancelBackgroundCompressor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compress All Now 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property FolderWatcherCardCompressAllNow() As String
            Get
                Return ResourceManager.GetString("FolderWatcherCardCompressAllNow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Last analysed 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property FolderWatcherCardLastAnalysed() As String
            Get
                Return ResourceManager.GetString("FolderWatcherCardLastAnalysed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 saved 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property FolderWatcherCardSaved() As String
            Get
                Return ResourceManager.GetString("FolderWatcherCardSaved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add Folder to Queue 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property HomePageAddFolder() As String
            Get
                Return ResourceManager.GetString("HomePageAddFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compress Selected 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property HomePageCompressSelected() As String
            Get
                Return ResourceManager.GetString("HomePageCompressSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Results State 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property HomePageResultsState() As String
            Get
                Return ResourceManager.GetString("HomePageResultsState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Working 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property HomePageWorking() As String
            Get
                Return ResourceManager.GetString("HomePageWorking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Welcome 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property MessageWelcome() As String
            Get
                Return ResourceManager.GetString("MessageWelcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Database Results 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PageDatabaseResults() As String
            Get
                Return ResourceManager.GetString("PageDatabaseResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Watched Folders 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PageFolderWatcherCardWatchedFoldersName() As String
            Get
                Return ResourceManager.GetString("PageFolderWatcherCardWatchedFoldersName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PageSettingsName() As String
            Get
                Return ResourceManager.GetString("PageSettingsName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 WatcherPage 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PageWatcherName() As String
            Get
                Return ResourceManager.GetString("PageWatcherName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Apply to all 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PendingCompressionApplyAll() As String
            Get
                Return ResourceManager.GetString("PendingCompressionApplyAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compression Mode 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PendingCompressionCompressionMode() As String
            Get
                Return ResourceManager.GetString("PendingCompressionCompressionMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Configuration 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PendingCompressionConfiguration() As String
            Get
                Return ResourceManager.GetString("PendingCompressionConfiguration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Skip file types likely to compress poorly 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PendingCompressionConfigurationSkipFileTypesLikelyPoorly() As String
            Get
                Return ResourceManager.GetString("PendingCompressionConfigurationSkipFileTypesLikelyPoorly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 For Steam Games:
        '''skips files based on database results
        '''
        '''For Non-Steam Folders:
        '''skips files based on compression estimate 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PendingCompressionConfigurationSkipFileTypesLikelyPoorlyTip() As String
            Get
                Return ResourceManager.GetString("PendingCompressionConfigurationSkipFileTypesLikelyPoorlyTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Skip file types specified in settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PendingCompressionConfigurationSkipFileTypesSpecified() As String
            Get
                Return ResourceManager.GetString("PendingCompressionConfigurationSkipFileTypesSpecified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LZX 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PendingCompressionModeLZX() As String
            Get
                Return ResourceManager.GetString("PendingCompressionModeLZX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 XPRESS 4K 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PendingCompressionModeXPRESS4K() As String
            Get
                Return ResourceManager.GetString("PendingCompressionModeXPRESS4K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Watch folder for changes 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PendingCompressionWatchFolderChanges() As String
            Get
                Return ResourceManager.GetString("PendingCompressionWatchFolderChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 XPRESS 16K 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PendingCompressionXPRESSMode16K() As String
            Get
                Return ResourceManager.GetString("PendingCompressionXPRESSMode16K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 XPRESS 8K 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property PendingCompressionXPRESSMode8K() As String
            Get
                Return ResourceManager.GetString("PendingCompressionXPRESSMode8K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0:0} days ago 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property RelativeTimeDaysAgo() As String
            Get
                Return ResourceManager.GetString("RelativeTimeDaysAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0:0} hours ago 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property RelativeTimeHoursAgo() As String
            Get
                Return ResourceManager.GetString("RelativeTimeHoursAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 just now 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property RelativeTimeJustNow() As String
            Get
                Return ResourceManager.GetString("RelativeTimeJustNow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0:0} minutes ago 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property RelativeTimeMinutesAgo() As String
            Get
                Return ResourceManager.GetString("RelativeTimeMinutesAgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Unknown 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property RelativeTimeUnknown() As String
            Get
                Return ResourceManager.GetString("RelativeTimeUnknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 After 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ResultsTemplateAfter() As String
            Get
                Return ResourceManager.GetString("ResultsTemplateAfter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Before 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ResultsTemplateBefore() As String
            Get
                Return ResourceManager.GetString("ResultsTemplateBefore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compress Again 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ResultsTemplateCompressAgain() As String
            Get
                Return ResourceManager.GetString("ResultsTemplateCompressAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compression Mode 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ResultsTemplateCompressionMode() As String
            Get
                Return ResourceManager.GetString("ResultsTemplateCompressionMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compression Summary 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ResultsTemplateCompressionSummary() As String
            Get
                Return ResourceManager.GetString("ResultsTemplateCompressionSummary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Files Compressed 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ResultsTemplateFilesCompressed() As String
            Get
                Return ResourceManager.GetString("ResultsTemplateFilesCompressed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Space Saved 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ResultsTemplateSpaceSaved() As String
            Get
                Return ResourceManager.GetString("ResultsTemplateSpaceSaved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Submit Results 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ResultsTemplateSubmitResults() As String
            Get
                Return ResourceManager.GetString("ResultsTemplateSubmitResults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Uncompress 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property ResultsTemplateUncompress() As String
            Get
                Return ResourceManager.GetString("ResultsTemplateUncompress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Background Watcher Settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsBackgroundWatcherSettings() As String
            Get
                Return ResourceManager.GetString("SettingsBackgroundWatcherSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compress folders:  的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsBackgroundWatcherSettingsCompressFolders() As String
            Get
                Return ResourceManager.GetString("SettingsBackgroundWatcherSettingsCompressFolders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Monitor compressed folders for changes 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsBackgroundWatcherSettingsFoldersChanges() As String
            Get
                Return ResourceManager.GetString("SettingsBackgroundWatcherSettingsFoldersChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 at 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsBackgroundWatcherSettingsTimeAt() As String
            Get
                Return ResourceManager.GetString("SettingsBackgroundWatcherSettingsTimeAt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 day(s) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsBackgroundWatcherSettingsTimeDay() As String
            Get
                Return ResourceManager.GetString("SettingsBackgroundWatcherSettingsTimeDay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 every 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsBackgroundWatcherSettingsTimeEvery() As String
            Get
                Return ResourceManager.GetString("SettingsBackgroundWatcherSettingsTimeEvery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Compression Settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsCompressionSettingsCompressionSettings() As String
            Get
                Return ResourceManager.GetString("SettingsCompressionSettingsCompressionSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 HDDs only use 1 thread 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsCompressionSettingsHDDThread() As String
            Get
                Return ResourceManager.GetString("SettingsCompressionSettingsHDDThread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Maximum Compression Threads 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsCompressionSettingsMaxThreads() As String
            Get
                Return ResourceManager.GetString("SettingsCompressionSettingsMaxThreads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Estimate Compression for non-Steam Folders (beta) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsCompressionSettingsNonSteamFolders() As String
            Get
                Return ResourceManager.GetString("SettingsCompressionSettingsNonSteamFolders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Filetype Management 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsFiletypeManagement() As String
            Get
                Return ResourceManager.GetString("SettingsFiletypeManagement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 high 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsFiletypeManagementAgressionHigh() As String
            Get
                Return ResourceManager.GetString("SettingsFiletypeManagementAgressionHigh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 low 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsFiletypeManagementAgressionLow() As String
            Get
                Return ResourceManager.GetString("SettingsFiletypeManagementAgressionLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 medium 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsFiletypeManagementAgressionMedium() As String
            Get
                Return ResourceManager.GetString("SettingsFiletypeManagementAgressionMedium", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 For Steam games only.When choosing to skip user-submitted filetypes, this setting determines how many submissions are required for each filetype to consider skipping it. &apos;low&apos; is generally best, as higher options run the risk of skipping files that would otherwise compress well. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsFiletypeManagementAgressionTip() As String
            Get
                Return ResourceManager.GetString("SettingsFiletypeManagementAgressionTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Manage local skipped filetypes 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsFiletypeManagementLocalSkipFiletypes() As String
            Get
                Return ResourceManager.GetString("SettingsFiletypeManagementLocalSkipFiletypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Agression of online skiplist 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsFiletypeManagementOnlineSkiplistAgression() As String
            Get
                Return ResourceManager.GetString("SettingsFiletypeManagementOnlineSkiplistAgression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 System Integration 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsSystemIntegration() As String
            Get
                Return ResourceManager.GetString("SettingsSystemIntegration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Show notification on completion 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsSystemIntegrationNotificationOnCompletion() As String
            Get
                Return ResourceManager.GetString("SettingsSystemIntegrationNotificationOnCompletion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add to right-click context menu 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsSystemIntegrationRightClickMenu() As String
            Get
                Return ResourceManager.GetString("SettingsSystemIntegrationRightClickMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add to start menu 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsSystemIntegrationStartMenu() As String
            Get
                Return ResourceManager.GetString("SettingsSystemIntegrationStartMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Start CompactGUI in system tray 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsSystemIntegrationSystemTrayStartup() As String
            Get
                Return ResourceManager.GetString("SettingsSystemIntegrationSystemTrayStartup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 UI Settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsUiSettings() As String
            Get
                Return ResourceManager.GetString("SettingsUiSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Always show details on Compression Mode buttons 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsUiSettingsCompressionButtons() As String
            Get
                Return ResourceManager.GetString("SettingsUiSettingsCompressionButtons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Language (Requires Restart) 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsUiSettingsLanguageChangedLabel() As String
            Get
                Return ResourceManager.GetString("SettingsUiSettingsLanguageChangedLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Language changed successfully. You may need to restart the application for all changes to take effect. 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsUiSettingsLanguageChangedMsg() As String
            Get
                Return ResourceManager.GetString("SettingsUiSettingsLanguageChangedMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Language Changed 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsUiSettingsLanguageChangeTitle() As String
            Get
                Return ResourceManager.GetString("SettingsUiSettingsLanguageChangeTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Update Settings 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsUpdateSettings() As String
            Get
                Return ResourceManager.GetString("SettingsUpdateSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Check for pre-release updates 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property SettingsUpdateSettingsCheckPreUpdates() As String
            Get
                Return ResourceManager.GetString("SettingsUpdateSettingsCheckPreUpdates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 edit 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property UniEdit() As String
            Get
                Return ResourceManager.GetString("UniEdit", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
